/*
Sonatype Guide API

Testing AGPGovernanceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sonatypeguide

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatypeguide "github.com/sonatype-nexus-community/sonatype-guide-api-client-go"
)

func Test_sonatypeguide_AGPGovernanceAPIService(t *testing.T) {

	configuration := sonatypeguide.NewConfiguration()
	apiClient := sonatypeguide.NewAPIClient(configuration)

	t.Run("Test AGPGovernanceAPIService DeleteRepoConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		httpRes, err := apiClient.AGPGovernanceAPI.DeleteRepoConfig(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService GetOrgConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AGPGovernanceAPI.GetOrgConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService GetOrgEffectiveConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AGPGovernanceAPI.GetOrgEffectiveConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService GetRepoConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		resp, httpRes, err := apiClient.AGPGovernanceAPI.GetRepoConfig(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService GetRepoEffectiveConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		resp, httpRes, err := apiClient.AGPGovernanceAPI.GetRepoEffectiveConfig(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService OpenRemovalPr", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		resp, httpRes, err := apiClient.AGPGovernanceAPI.OpenRemovalPr(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService Pause", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		httpRes, err := apiClient.AGPGovernanceAPI.Pause(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService Resume", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		httpRes, err := apiClient.AGPGovernanceAPI.Resume(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService UpdateOrgConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AGPGovernanceAPI.UpdateOrgConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AGPGovernanceAPIService UpdateRepoConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var installationRepoId int64

		resp, httpRes, err := apiClient.AGPGovernanceAPI.UpdateRepoConfig(context.Background(), installationRepoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
