/*
Sonatype Guide API

Testing OSSIndexCompatibilityAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sonatypeguide

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatypeguide "github.com/sonatype-nexus-community/sonatype-guide-api-client-go"
)

func Test_sonatypeguide_OSSIndexCompatibilityAPIService(t *testing.T) {

	configuration := sonatypeguide.NewConfiguration()
	apiClient := sonatypeguide.NewAPIClient(configuration)

	t.Run("Test OSSIndexCompatibilityAPIService GetComponentReport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OSSIndexCompatibilityAPI.GetComponentReport(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OSSIndexCompatibilityAPIService GetComponentReport1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OSSIndexCompatibilityAPI.GetComponentReport1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OSSIndexCompatibilityAPIService GetComponentReports", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OSSIndexCompatibilityAPI.GetComponentReports(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OSSIndexCompatibilityAPIService GetComponentReports1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OSSIndexCompatibilityAPI.GetComponentReports1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OSSIndexCompatibilityAPIService GetVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OSSIndexCompatibilityAPI.GetVersion(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
