/*
Sonatype Guide API

Testing CurrentUserOrganizationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v1

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatypeguide "github.com/sonatype-nexus-community/sonatype-guide-api-client-go/v1"
)

func Test_v1_CurrentUserOrganizationAPIService(t *testing.T) {

	configuration := sonatypeguide.NewConfiguration()
	apiClient := sonatypeguide.NewAPIClient(configuration)

	t.Run("Test CurrentUserOrganizationAPIService AcceptInvitation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var invitationToken string

		httpRes, err := apiClient.CurrentUserOrganizationAPI.AcceptInvitation(context.Background(), invitationToken).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService BulkRemoveMembersOrInvitations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.BulkRemoveMembersOrInvitations(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService GetCurrentUserOrganization", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.GetCurrentUserOrganization(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService InviteUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.InviteUsers(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService LeaveOrganization", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.LeaveOrganization(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService RemoveMemberOrInvitation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var email string

		httpRes, err := apiClient.CurrentUserOrganizationAPI.RemoveMemberOrInvitation(context.Background(), email).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService RetrieveOrganizationMembersAsCsv", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.RetrieveOrganizationMembersAsCsv(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CurrentUserOrganizationAPIService UpdateOrganization", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CurrentUserOrganizationAPI.UpdateOrganization(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
