/*
Sonatype Guide API

Testing RecommendationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sonatypeguide

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatypeguide "github.com/sonatype-nexus-community/sonatype-guide-api-client-go"
)

func Test_sonatypeguide_RecommendationsAPIService(t *testing.T) {

	configuration := sonatypeguide.NewConfiguration()
	apiClient := sonatypeguide.NewAPIClient(configuration)

	t.Run("Test RecommendationsAPIService GetRecommendations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RecommendationsAPI.GetRecommendations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
