/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the RecommendationVulnerableMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecommendationVulnerableMethod{}

// RecommendationVulnerableMethod struct for RecommendationVulnerableMethod
type RecommendationVulnerableMethod struct {
	MethodSignatures []MethodSignature `json:"methodSignatures,omitempty"`
	Refid *string `json:"refid,omitempty"`
}

// NewRecommendationVulnerableMethod instantiates a new RecommendationVulnerableMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendationVulnerableMethod() *RecommendationVulnerableMethod {
	this := RecommendationVulnerableMethod{}
	return &this
}

// NewRecommendationVulnerableMethodWithDefaults instantiates a new RecommendationVulnerableMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendationVulnerableMethodWithDefaults() *RecommendationVulnerableMethod {
	this := RecommendationVulnerableMethod{}
	return &this
}

// GetMethodSignatures returns the MethodSignatures field value if set, zero value otherwise.
func (o *RecommendationVulnerableMethod) GetMethodSignatures() []MethodSignature {
	if o == nil || IsNil(o.MethodSignatures) {
		var ret []MethodSignature
		return ret
	}
	return o.MethodSignatures
}

// GetMethodSignaturesOk returns a tuple with the MethodSignatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationVulnerableMethod) GetMethodSignaturesOk() ([]MethodSignature, bool) {
	if o == nil || IsNil(o.MethodSignatures) {
		return nil, false
	}
	return o.MethodSignatures, true
}

// HasMethodSignatures returns a boolean if a field has been set.
func (o *RecommendationVulnerableMethod) HasMethodSignatures() bool {
	if o != nil && !IsNil(o.MethodSignatures) {
		return true
	}

	return false
}

// SetMethodSignatures gets a reference to the given []MethodSignature and assigns it to the MethodSignatures field.
func (o *RecommendationVulnerableMethod) SetMethodSignatures(v []MethodSignature) {
	o.MethodSignatures = v
}

// GetRefid returns the Refid field value if set, zero value otherwise.
func (o *RecommendationVulnerableMethod) GetRefid() string {
	if o == nil || IsNil(o.Refid) {
		var ret string
		return ret
	}
	return *o.Refid
}

// GetRefidOk returns a tuple with the Refid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationVulnerableMethod) GetRefidOk() (*string, bool) {
	if o == nil || IsNil(o.Refid) {
		return nil, false
	}
	return o.Refid, true
}

// HasRefid returns a boolean if a field has been set.
func (o *RecommendationVulnerableMethod) HasRefid() bool {
	if o != nil && !IsNil(o.Refid) {
		return true
	}

	return false
}

// SetRefid gets a reference to the given string and assigns it to the Refid field.
func (o *RecommendationVulnerableMethod) SetRefid(v string) {
	o.Refid = &v
}

func (o RecommendationVulnerableMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecommendationVulnerableMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MethodSignatures) {
		toSerialize["methodSignatures"] = o.MethodSignatures
	}
	if !IsNil(o.Refid) {
		toSerialize["refid"] = o.Refid
	}
	return toSerialize, nil
}

type NullableRecommendationVulnerableMethod struct {
	value *RecommendationVulnerableMethod
	isSet bool
}

func (v NullableRecommendationVulnerableMethod) Get() *RecommendationVulnerableMethod {
	return v.value
}

func (v *NullableRecommendationVulnerableMethod) Set(val *RecommendationVulnerableMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendationVulnerableMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendationVulnerableMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendationVulnerableMethod(val *RecommendationVulnerableMethod) *NullableRecommendationVulnerableMethod {
	return &NullableRecommendationVulnerableMethod{value: val, isSet: true}
}

func (v NullableRecommendationVulnerableMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendationVulnerableMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


