/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202605
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the ComponentReportPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentReportPost{}

// ComponentReportPost struct for ComponentReportPost
type ComponentReportPost struct {
	Coordinates *string `json:"coordinates,omitempty"`
	Description *string `json:"description,omitempty"`
	Reference *string `json:"reference,omitempty"`
	Vulnerabilities []OssiVulnerabilityPost `json:"vulnerabilities,omitempty"`
}

// NewComponentReportPost instantiates a new ComponentReportPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentReportPost() *ComponentReportPost {
	this := ComponentReportPost{}
	return &this
}

// NewComponentReportPostWithDefaults instantiates a new ComponentReportPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentReportPostWithDefaults() *ComponentReportPost {
	this := ComponentReportPost{}
	return &this
}

// GetCoordinates returns the Coordinates field value if set, zero value otherwise.
func (o *ComponentReportPost) GetCoordinates() string {
	if o == nil || IsNil(o.Coordinates) {
		var ret string
		return ret
	}
	return *o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentReportPost) GetCoordinatesOk() (*string, bool) {
	if o == nil || IsNil(o.Coordinates) {
		return nil, false
	}
	return o.Coordinates, true
}

// HasCoordinates returns a boolean if a field has been set.
func (o *ComponentReportPost) HasCoordinates() bool {
	if o != nil && !IsNil(o.Coordinates) {
		return true
	}

	return false
}

// SetCoordinates gets a reference to the given string and assigns it to the Coordinates field.
func (o *ComponentReportPost) SetCoordinates(v string) {
	o.Coordinates = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ComponentReportPost) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentReportPost) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ComponentReportPost) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ComponentReportPost) SetDescription(v string) {
	o.Description = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *ComponentReportPost) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentReportPost) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *ComponentReportPost) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *ComponentReportPost) SetReference(v string) {
	o.Reference = &v
}

// GetVulnerabilities returns the Vulnerabilities field value if set, zero value otherwise.
func (o *ComponentReportPost) GetVulnerabilities() []OssiVulnerabilityPost {
	if o == nil || IsNil(o.Vulnerabilities) {
		var ret []OssiVulnerabilityPost
		return ret
	}
	return o.Vulnerabilities
}

// GetVulnerabilitiesOk returns a tuple with the Vulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentReportPost) GetVulnerabilitiesOk() ([]OssiVulnerabilityPost, bool) {
	if o == nil || IsNil(o.Vulnerabilities) {
		return nil, false
	}
	return o.Vulnerabilities, true
}

// HasVulnerabilities returns a boolean if a field has been set.
func (o *ComponentReportPost) HasVulnerabilities() bool {
	if o != nil && !IsNil(o.Vulnerabilities) {
		return true
	}

	return false
}

// SetVulnerabilities gets a reference to the given []OssiVulnerabilityPost and assigns it to the Vulnerabilities field.
func (o *ComponentReportPost) SetVulnerabilities(v []OssiVulnerabilityPost) {
	o.Vulnerabilities = v
}

func (o ComponentReportPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentReportPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Coordinates) {
		toSerialize["coordinates"] = o.Coordinates
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Vulnerabilities) {
		toSerialize["vulnerabilities"] = o.Vulnerabilities
	}
	return toSerialize, nil
}

type NullableComponentReportPost struct {
	value *ComponentReportPost
	isSet bool
}

func (v NullableComponentReportPost) Get() *ComponentReportPost {
	return v.value
}

func (v *NullableComponentReportPost) Set(val *ComponentReportPost) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentReportPost) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentReportPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentReportPost(val *ComponentReportPost) *NullableComponentReportPost {
	return &NullableComponentReportPost{value: val, isSet: true}
}

func (v NullableComponentReportPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentReportPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


