/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// checks if the ComponentDetailDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentDetailDocument{}

// ComponentDetailDocument struct for ComponentDetailDocument
type ComponentDetailDocument struct {
	Categories []string `json:"categories,omitempty"`
	Components []ComponentArtifact `json:"components,omitempty"`
	DirectDependencies []string `json:"directDependencies,omitempty"`
	Format *string `json:"format,omitempty"`
	IsMalware *bool `json:"isMalware,omitempty"`
	LatestStable *bool `json:"latestStable,omitempty"`
	Licenses []ComponentLicense `json:"licenses,omitempty"`
	MaxCvss *float64 `json:"maxCvss,omitempty"`
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	OriginId *string `json:"originId,omitempty"`
	PublishedDate *time.Time `json:"publishedDate,omitempty"`
	RegistryLink *string `json:"registryLink,omitempty"`
	Version *string `json:"version,omitempty"`
	VersionScore *int32 `json:"versionScore,omitempty"`
}

// NewComponentDetailDocument instantiates a new ComponentDetailDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentDetailDocument() *ComponentDetailDocument {
	this := ComponentDetailDocument{}
	return &this
}

// NewComponentDetailDocumentWithDefaults instantiates a new ComponentDetailDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentDetailDocumentWithDefaults() *ComponentDetailDocument {
	this := ComponentDetailDocument{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *ComponentDetailDocument) SetCategories(v []string) {
	o.Categories = v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetComponents() []ComponentArtifact {
	if o == nil || IsNil(o.Components) {
		var ret []ComponentArtifact
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetComponentsOk() ([]ComponentArtifact, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []ComponentArtifact and assigns it to the Components field.
func (o *ComponentDetailDocument) SetComponents(v []ComponentArtifact) {
	o.Components = v
}

// GetDirectDependencies returns the DirectDependencies field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetDirectDependencies() []string {
	if o == nil || IsNil(o.DirectDependencies) {
		var ret []string
		return ret
	}
	return o.DirectDependencies
}

// GetDirectDependenciesOk returns a tuple with the DirectDependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetDirectDependenciesOk() ([]string, bool) {
	if o == nil || IsNil(o.DirectDependencies) {
		return nil, false
	}
	return o.DirectDependencies, true
}

// HasDirectDependencies returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasDirectDependencies() bool {
	if o != nil && !IsNil(o.DirectDependencies) {
		return true
	}

	return false
}

// SetDirectDependencies gets a reference to the given []string and assigns it to the DirectDependencies field.
func (o *ComponentDetailDocument) SetDirectDependencies(v []string) {
	o.DirectDependencies = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ComponentDetailDocument) SetFormat(v string) {
	o.Format = &v
}

// GetIsMalware returns the IsMalware field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetIsMalware() bool {
	if o == nil || IsNil(o.IsMalware) {
		var ret bool
		return ret
	}
	return *o.IsMalware
}

// GetIsMalwareOk returns a tuple with the IsMalware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetIsMalwareOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMalware) {
		return nil, false
	}
	return o.IsMalware, true
}

// HasIsMalware returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasIsMalware() bool {
	if o != nil && !IsNil(o.IsMalware) {
		return true
	}

	return false
}

// SetIsMalware gets a reference to the given bool and assigns it to the IsMalware field.
func (o *ComponentDetailDocument) SetIsMalware(v bool) {
	o.IsMalware = &v
}

// GetLatestStable returns the LatestStable field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetLatestStable() bool {
	if o == nil || IsNil(o.LatestStable) {
		var ret bool
		return ret
	}
	return *o.LatestStable
}

// GetLatestStableOk returns a tuple with the LatestStable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetLatestStableOk() (*bool, bool) {
	if o == nil || IsNil(o.LatestStable) {
		return nil, false
	}
	return o.LatestStable, true
}

// HasLatestStable returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasLatestStable() bool {
	if o != nil && !IsNil(o.LatestStable) {
		return true
	}

	return false
}

// SetLatestStable gets a reference to the given bool and assigns it to the LatestStable field.
func (o *ComponentDetailDocument) SetLatestStable(v bool) {
	o.LatestStable = &v
}

// GetLicenses returns the Licenses field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetLicenses() []ComponentLicense {
	if o == nil || IsNil(o.Licenses) {
		var ret []ComponentLicense
		return ret
	}
	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetLicensesOk() ([]ComponentLicense, bool) {
	if o == nil || IsNil(o.Licenses) {
		return nil, false
	}
	return o.Licenses, true
}

// HasLicenses returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasLicenses() bool {
	if o != nil && !IsNil(o.Licenses) {
		return true
	}

	return false
}

// SetLicenses gets a reference to the given []ComponentLicense and assigns it to the Licenses field.
func (o *ComponentDetailDocument) SetLicenses(v []ComponentLicense) {
	o.Licenses = v
}

// GetMaxCvss returns the MaxCvss field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetMaxCvss() float64 {
	if o == nil || IsNil(o.MaxCvss) {
		var ret float64
		return ret
	}
	return *o.MaxCvss
}

// GetMaxCvssOk returns a tuple with the MaxCvss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetMaxCvssOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxCvss) {
		return nil, false
	}
	return o.MaxCvss, true
}

// HasMaxCvss returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasMaxCvss() bool {
	if o != nil && !IsNil(o.MaxCvss) {
		return true
	}

	return false
}

// SetMaxCvss gets a reference to the given float64 and assigns it to the MaxCvss field.
func (o *ComponentDetailDocument) SetMaxCvss(v float64) {
	o.MaxCvss = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComponentDetailDocument) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ComponentDetailDocument) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOriginId returns the OriginId field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetOriginId() string {
	if o == nil || IsNil(o.OriginId) {
		var ret string
		return ret
	}
	return *o.OriginId
}

// GetOriginIdOk returns a tuple with the OriginId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetOriginIdOk() (*string, bool) {
	if o == nil || IsNil(o.OriginId) {
		return nil, false
	}
	return o.OriginId, true
}

// HasOriginId returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasOriginId() bool {
	if o != nil && !IsNil(o.OriginId) {
		return true
	}

	return false
}

// SetOriginId gets a reference to the given string and assigns it to the OriginId field.
func (o *ComponentDetailDocument) SetOriginId(v string) {
	o.OriginId = &v
}

// GetPublishedDate returns the PublishedDate field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetPublishedDate() time.Time {
	if o == nil || IsNil(o.PublishedDate) {
		var ret time.Time
		return ret
	}
	return *o.PublishedDate
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetPublishedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedDate) {
		return nil, false
	}
	return o.PublishedDate, true
}

// HasPublishedDate returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasPublishedDate() bool {
	if o != nil && !IsNil(o.PublishedDate) {
		return true
	}

	return false
}

// SetPublishedDate gets a reference to the given time.Time and assigns it to the PublishedDate field.
func (o *ComponentDetailDocument) SetPublishedDate(v time.Time) {
	o.PublishedDate = &v
}

// GetRegistryLink returns the RegistryLink field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetRegistryLink() string {
	if o == nil || IsNil(o.RegistryLink) {
		var ret string
		return ret
	}
	return *o.RegistryLink
}

// GetRegistryLinkOk returns a tuple with the RegistryLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetRegistryLinkOk() (*string, bool) {
	if o == nil || IsNil(o.RegistryLink) {
		return nil, false
	}
	return o.RegistryLink, true
}

// HasRegistryLink returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasRegistryLink() bool {
	if o != nil && !IsNil(o.RegistryLink) {
		return true
	}

	return false
}

// SetRegistryLink gets a reference to the given string and assigns it to the RegistryLink field.
func (o *ComponentDetailDocument) SetRegistryLink(v string) {
	o.RegistryLink = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ComponentDetailDocument) SetVersion(v string) {
	o.Version = &v
}

// GetVersionScore returns the VersionScore field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetVersionScore() int32 {
	if o == nil || IsNil(o.VersionScore) {
		var ret int32
		return ret
	}
	return *o.VersionScore
}

// GetVersionScoreOk returns a tuple with the VersionScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetVersionScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.VersionScore) {
		return nil, false
	}
	return o.VersionScore, true
}

// HasVersionScore returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasVersionScore() bool {
	if o != nil && !IsNil(o.VersionScore) {
		return true
	}

	return false
}

// SetVersionScore gets a reference to the given int32 and assigns it to the VersionScore field.
func (o *ComponentDetailDocument) SetVersionScore(v int32) {
	o.VersionScore = &v
}

func (o ComponentDetailDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentDetailDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	if !IsNil(o.DirectDependencies) {
		toSerialize["directDependencies"] = o.DirectDependencies
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.IsMalware) {
		toSerialize["isMalware"] = o.IsMalware
	}
	if !IsNil(o.LatestStable) {
		toSerialize["latestStable"] = o.LatestStable
	}
	if !IsNil(o.Licenses) {
		toSerialize["licenses"] = o.Licenses
	}
	if !IsNil(o.MaxCvss) {
		toSerialize["maxCvss"] = o.MaxCvss
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.OriginId) {
		toSerialize["originId"] = o.OriginId
	}
	if !IsNil(o.PublishedDate) {
		toSerialize["publishedDate"] = o.PublishedDate
	}
	if !IsNil(o.RegistryLink) {
		toSerialize["registryLink"] = o.RegistryLink
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.VersionScore) {
		toSerialize["versionScore"] = o.VersionScore
	}
	return toSerialize, nil
}

type NullableComponentDetailDocument struct {
	value *ComponentDetailDocument
	isSet bool
}

func (v NullableComponentDetailDocument) Get() *ComponentDetailDocument {
	return v.value
}

func (v *NullableComponentDetailDocument) Set(val *ComponentDetailDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentDetailDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentDetailDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentDetailDocument(val *ComponentDetailDocument) *NullableComponentDetailDocument {
	return &NullableComponentDetailDocument{value: val, isSet: true}
}

func (v NullableComponentDetailDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentDetailDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


