/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202606
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
	"time"
)

// checks if the OrganizationMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationMembersResponse{}

// OrganizationMembersResponse struct for OrganizationMembersResponse
type OrganizationMembersResponse struct {
	Avatar *string `json:"avatar,omitempty"`
	Email *string `json:"email,omitempty"`
	InvitedHistory []time.Time `json:"invitedHistory,omitempty"`
	JoinedAt *time.Time `json:"joinedAt,omitempty"`
	LastActive *time.Time `json:"lastActive,omitempty"`
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewOrganizationMembersResponse instantiates a new OrganizationMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationMembersResponse() *OrganizationMembersResponse {
	this := OrganizationMembersResponse{}
	return &this
}

// NewOrganizationMembersResponseWithDefaults instantiates a new OrganizationMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationMembersResponseWithDefaults() *OrganizationMembersResponse {
	this := OrganizationMembersResponse{}
	return &this
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *OrganizationMembersResponse) SetAvatar(v string) {
	o.Avatar = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OrganizationMembersResponse) SetEmail(v string) {
	o.Email = &v
}

// GetInvitedHistory returns the InvitedHistory field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetInvitedHistory() []time.Time {
	if o == nil || IsNil(o.InvitedHistory) {
		var ret []time.Time
		return ret
	}
	return o.InvitedHistory
}

// GetInvitedHistoryOk returns a tuple with the InvitedHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetInvitedHistoryOk() ([]time.Time, bool) {
	if o == nil || IsNil(o.InvitedHistory) {
		return nil, false
	}
	return o.InvitedHistory, true
}

// HasInvitedHistory returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasInvitedHistory() bool {
	if o != nil && !IsNil(o.InvitedHistory) {
		return true
	}

	return false
}

// SetInvitedHistory gets a reference to the given []time.Time and assigns it to the InvitedHistory field.
func (o *OrganizationMembersResponse) SetInvitedHistory(v []time.Time) {
	o.InvitedHistory = v
}

// GetJoinedAt returns the JoinedAt field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetJoinedAt() time.Time {
	if o == nil || IsNil(o.JoinedAt) {
		var ret time.Time
		return ret
	}
	return *o.JoinedAt
}

// GetJoinedAtOk returns a tuple with the JoinedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetJoinedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.JoinedAt) {
		return nil, false
	}
	return o.JoinedAt, true
}

// HasJoinedAt returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasJoinedAt() bool {
	if o != nil && !IsNil(o.JoinedAt) {
		return true
	}

	return false
}

// SetJoinedAt gets a reference to the given time.Time and assigns it to the JoinedAt field.
func (o *OrganizationMembersResponse) SetJoinedAt(v time.Time) {
	o.JoinedAt = &v
}

// GetLastActive returns the LastActive field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetLastActive() time.Time {
	if o == nil || IsNil(o.LastActive) {
		var ret time.Time
		return ret
	}
	return *o.LastActive
}

// GetLastActiveOk returns a tuple with the LastActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetLastActiveOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastActive) {
		return nil, false
	}
	return o.LastActive, true
}

// HasLastActive returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasLastActive() bool {
	if o != nil && !IsNil(o.LastActive) {
		return true
	}

	return false
}

// SetLastActive gets a reference to the given time.Time and assigns it to the LastActive field.
func (o *OrganizationMembersResponse) SetLastActive(v time.Time) {
	o.LastActive = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationMembersResponse) SetName(v string) {
	o.Name = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *OrganizationMembersResponse) SetRole(v string) {
	o.Role = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OrganizationMembersResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationMembersResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OrganizationMembersResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OrganizationMembersResponse) SetStatus(v string) {
	o.Status = &v
}

func (o OrganizationMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.InvitedHistory) {
		toSerialize["invitedHistory"] = o.InvitedHistory
	}
	if !IsNil(o.JoinedAt) {
		toSerialize["joinedAt"] = o.JoinedAt
	}
	if !IsNil(o.LastActive) {
		toSerialize["lastActive"] = o.LastActive
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableOrganizationMembersResponse struct {
	value *OrganizationMembersResponse
	isSet bool
}

func (v NullableOrganizationMembersResponse) Get() *OrganizationMembersResponse {
	return v.value
}

func (v *NullableOrganizationMembersResponse) Set(val *OrganizationMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationMembersResponse(val *OrganizationMembersResponse) *NullableOrganizationMembersResponse {
	return &NullableOrganizationMembersResponse{value: val, isSet: true}
}

func (v NullableOrganizationMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


