/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the OrgActivityLogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgActivityLogResponse{}

// OrgActivityLogResponse struct for OrgActivityLogResponse
type OrgActivityLogResponse struct {
	Events []OrgActivityLogEntry `json:"events,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
	TotalCount *int64 `json:"totalCount,omitempty"`
	TotalPages *int32 `json:"totalPages,omitempty"`
}

// NewOrgActivityLogResponse instantiates a new OrgActivityLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgActivityLogResponse() *OrgActivityLogResponse {
	this := OrgActivityLogResponse{}
	return &this
}

// NewOrgActivityLogResponseWithDefaults instantiates a new OrgActivityLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgActivityLogResponseWithDefaults() *OrgActivityLogResponse {
	this := OrgActivityLogResponse{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *OrgActivityLogResponse) GetEvents() []OrgActivityLogEntry {
	if o == nil || IsNil(o.Events) {
		var ret []OrgActivityLogEntry
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgActivityLogResponse) GetEventsOk() ([]OrgActivityLogEntry, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *OrgActivityLogResponse) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []OrgActivityLogEntry and assigns it to the Events field.
func (o *OrgActivityLogResponse) SetEvents(v []OrgActivityLogEntry) {
	o.Events = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *OrgActivityLogResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgActivityLogResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *OrgActivityLogResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *OrgActivityLogResponse) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *OrgActivityLogResponse) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgActivityLogResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *OrgActivityLogResponse) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *OrgActivityLogResponse) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *OrgActivityLogResponse) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgActivityLogResponse) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *OrgActivityLogResponse) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *OrgActivityLogResponse) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *OrgActivityLogResponse) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgActivityLogResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *OrgActivityLogResponse) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *OrgActivityLogResponse) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o OrgActivityLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgActivityLogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !IsNil(o.TotalPages) {
		toSerialize["totalPages"] = o.TotalPages
	}
	return toSerialize, nil
}

type NullableOrgActivityLogResponse struct {
	value *OrgActivityLogResponse
	isSet bool
}

func (v NullableOrgActivityLogResponse) Get() *OrgActivityLogResponse {
	return v.value
}

func (v *NullableOrgActivityLogResponse) Set(val *OrgActivityLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgActivityLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgActivityLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgActivityLogResponse(val *OrgActivityLogResponse) *NullableOrgActivityLogResponse {
	return &NullableOrgActivityLogResponse{value: val, isSet: true}
}

func (v NullableOrgActivityLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgActivityLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


