/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202605
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the RecommendationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecommendationResponse{}

// RecommendationResponse struct for RecommendationResponse
type RecommendationResponse struct {
	FromVersion *FromVersion `json:"fromVersion,omitempty"`
	ToVersions []RecommendedVersion `json:"toVersions,omitempty"`
}

// NewRecommendationResponse instantiates a new RecommendationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendationResponse() *RecommendationResponse {
	this := RecommendationResponse{}
	return &this
}

// NewRecommendationResponseWithDefaults instantiates a new RecommendationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendationResponseWithDefaults() *RecommendationResponse {
	this := RecommendationResponse{}
	return &this
}

// GetFromVersion returns the FromVersion field value if set, zero value otherwise.
func (o *RecommendationResponse) GetFromVersion() FromVersion {
	if o == nil || IsNil(o.FromVersion) {
		var ret FromVersion
		return ret
	}
	return *o.FromVersion
}

// GetFromVersionOk returns a tuple with the FromVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationResponse) GetFromVersionOk() (*FromVersion, bool) {
	if o == nil || IsNil(o.FromVersion) {
		return nil, false
	}
	return o.FromVersion, true
}

// HasFromVersion returns a boolean if a field has been set.
func (o *RecommendationResponse) HasFromVersion() bool {
	if o != nil && !IsNil(o.FromVersion) {
		return true
	}

	return false
}

// SetFromVersion gets a reference to the given FromVersion and assigns it to the FromVersion field.
func (o *RecommendationResponse) SetFromVersion(v FromVersion) {
	o.FromVersion = &v
}

// GetToVersions returns the ToVersions field value if set, zero value otherwise.
func (o *RecommendationResponse) GetToVersions() []RecommendedVersion {
	if o == nil || IsNil(o.ToVersions) {
		var ret []RecommendedVersion
		return ret
	}
	return o.ToVersions
}

// GetToVersionsOk returns a tuple with the ToVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendationResponse) GetToVersionsOk() ([]RecommendedVersion, bool) {
	if o == nil || IsNil(o.ToVersions) {
		return nil, false
	}
	return o.ToVersions, true
}

// HasToVersions returns a boolean if a field has been set.
func (o *RecommendationResponse) HasToVersions() bool {
	if o != nil && !IsNil(o.ToVersions) {
		return true
	}

	return false
}

// SetToVersions gets a reference to the given []RecommendedVersion and assigns it to the ToVersions field.
func (o *RecommendationResponse) SetToVersions(v []RecommendedVersion) {
	o.ToVersions = v
}

func (o RecommendationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecommendationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FromVersion) {
		toSerialize["fromVersion"] = o.FromVersion
	}
	if !IsNil(o.ToVersions) {
		toSerialize["toVersions"] = o.ToVersions
	}
	return toSerialize, nil
}

type NullableRecommendationResponse struct {
	value *RecommendationResponse
	isSet bool
}

func (v NullableRecommendationResponse) Get() *RecommendationResponse {
	return v.value
}

func (v *NullableRecommendationResponse) Set(val *RecommendationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendationResponse(val *RecommendationResponse) *NullableRecommendationResponse {
	return &NullableRecommendationResponse{value: val, isSet: true}
}

func (v NullableRecommendationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


