/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202605
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkRemoveMembersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkRemoveMembersRequest{}

// BulkRemoveMembersRequest struct for BulkRemoveMembersRequest
type BulkRemoveMembersRequest struct {
	Emails []string `json:"emails"`
}

type _BulkRemoveMembersRequest BulkRemoveMembersRequest

// NewBulkRemoveMembersRequest instantiates a new BulkRemoveMembersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkRemoveMembersRequest(emails []string) *BulkRemoveMembersRequest {
	this := BulkRemoveMembersRequest{}
	this.Emails = emails
	return &this
}

// NewBulkRemoveMembersRequestWithDefaults instantiates a new BulkRemoveMembersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkRemoveMembersRequestWithDefaults() *BulkRemoveMembersRequest {
	this := BulkRemoveMembersRequest{}
	return &this
}

// GetEmails returns the Emails field value
func (o *BulkRemoveMembersRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *BulkRemoveMembersRequest) GetEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *BulkRemoveMembersRequest) SetEmails(v []string) {
	o.Emails = v
}

func (o BulkRemoveMembersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkRemoveMembersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *BulkRemoveMembersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkRemoveMembersRequest := _BulkRemoveMembersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkRemoveMembersRequest)

	if err != nil {
		return err
	}

	*o = BulkRemoveMembersRequest(varBulkRemoveMembersRequest)

	return err
}

type NullableBulkRemoveMembersRequest struct {
	value *BulkRemoveMembersRequest
	isSet bool
}

func (v NullableBulkRemoveMembersRequest) Get() *BulkRemoveMembersRequest {
	return v.value
}

func (v *NullableBulkRemoveMembersRequest) Set(val *BulkRemoveMembersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkRemoveMembersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkRemoveMembersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkRemoveMembersRequest(val *BulkRemoveMembersRequest) *NullableBulkRemoveMembersRequest {
	return &NullableBulkRemoveMembersRequest{value: val, isSet: true}
}

func (v NullableBulkRemoveMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkRemoveMembersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


