/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the PlansResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlansResponse{}

// PlansResponse struct for PlansResponse
type PlansResponse struct {
	Plans []PlanInfo `json:"plans,omitempty"`
}

// NewPlansResponse instantiates a new PlansResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlansResponse() *PlansResponse {
	this := PlansResponse{}
	return &this
}

// NewPlansResponseWithDefaults instantiates a new PlansResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlansResponseWithDefaults() *PlansResponse {
	this := PlansResponse{}
	return &this
}

// GetPlans returns the Plans field value if set, zero value otherwise.
func (o *PlansResponse) GetPlans() []PlanInfo {
	if o == nil || IsNil(o.Plans) {
		var ret []PlanInfo
		return ret
	}
	return o.Plans
}

// GetPlansOk returns a tuple with the Plans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlansResponse) GetPlansOk() ([]PlanInfo, bool) {
	if o == nil || IsNil(o.Plans) {
		return nil, false
	}
	return o.Plans, true
}

// HasPlans returns a boolean if a field has been set.
func (o *PlansResponse) HasPlans() bool {
	if o != nil && !IsNil(o.Plans) {
		return true
	}

	return false
}

// SetPlans gets a reference to the given []PlanInfo and assigns it to the Plans field.
func (o *PlansResponse) SetPlans(v []PlanInfo) {
	o.Plans = v
}

func (o PlansResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlansResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plans) {
		toSerialize["plans"] = o.Plans
	}
	return toSerialize, nil
}

type NullablePlansResponse struct {
	value *PlansResponse
	isSet bool
}

func (v NullablePlansResponse) Get() *PlansResponse {
	return v.value
}

func (v *NullablePlansResponse) Set(val *PlansResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlansResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlansResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlansResponse(val *PlansResponse) *NullablePlansResponse {
	return &NullablePlansResponse{value: val, isSet: true}
}

func (v NullablePlansResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlansResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


