/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202606
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the ApiSearchResponseComponentDetailDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSearchResponseComponentDetailDocument{}

// ApiSearchResponseComponentDetailDocument struct for ApiSearchResponseComponentDetailDocument
type ApiSearchResponseComponentDetailDocument struct {
	Aggregations map[string]map[string]int64 `json:"aggregations,omitempty"`
	Hits []ComponentDetailDocument `json:"hits,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Total *int64 `json:"total,omitempty"`
}

// NewApiSearchResponseComponentDetailDocument instantiates a new ApiSearchResponseComponentDetailDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSearchResponseComponentDetailDocument() *ApiSearchResponseComponentDetailDocument {
	this := ApiSearchResponseComponentDetailDocument{}
	return &this
}

// NewApiSearchResponseComponentDetailDocumentWithDefaults instantiates a new ApiSearchResponseComponentDetailDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSearchResponseComponentDetailDocumentWithDefaults() *ApiSearchResponseComponentDetailDocument {
	this := ApiSearchResponseComponentDetailDocument{}
	return &this
}

// GetAggregations returns the Aggregations field value if set, zero value otherwise.
func (o *ApiSearchResponseComponentDetailDocument) GetAggregations() map[string]map[string]int64 {
	if o == nil || IsNil(o.Aggregations) {
		var ret map[string]map[string]int64
		return ret
	}
	return o.Aggregations
}

// GetAggregationsOk returns a tuple with the Aggregations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSearchResponseComponentDetailDocument) GetAggregationsOk() (map[string]map[string]int64, bool) {
	if o == nil || IsNil(o.Aggregations) {
		return map[string]map[string]int64{}, false
	}
	return o.Aggregations, true
}

// HasAggregations returns a boolean if a field has been set.
func (o *ApiSearchResponseComponentDetailDocument) HasAggregations() bool {
	if o != nil && !IsNil(o.Aggregations) {
		return true
	}

	return false
}

// SetAggregations gets a reference to the given map[string]map[string]int64 and assigns it to the Aggregations field.
func (o *ApiSearchResponseComponentDetailDocument) SetAggregations(v map[string]map[string]int64) {
	o.Aggregations = v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *ApiSearchResponseComponentDetailDocument) GetHits() []ComponentDetailDocument {
	if o == nil || IsNil(o.Hits) {
		var ret []ComponentDetailDocument
		return ret
	}
	return o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSearchResponseComponentDetailDocument) GetHitsOk() ([]ComponentDetailDocument, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *ApiSearchResponseComponentDetailDocument) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given []ComponentDetailDocument and assigns it to the Hits field.
func (o *ApiSearchResponseComponentDetailDocument) SetHits(v []ComponentDetailDocument) {
	o.Hits = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ApiSearchResponseComponentDetailDocument) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSearchResponseComponentDetailDocument) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ApiSearchResponseComponentDetailDocument) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ApiSearchResponseComponentDetailDocument) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ApiSearchResponseComponentDetailDocument) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSearchResponseComponentDetailDocument) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ApiSearchResponseComponentDetailDocument) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ApiSearchResponseComponentDetailDocument) SetOffset(v int32) {
	o.Offset = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ApiSearchResponseComponentDetailDocument) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSearchResponseComponentDetailDocument) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ApiSearchResponseComponentDetailDocument) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *ApiSearchResponseComponentDetailDocument) SetTotal(v int64) {
	o.Total = &v
}

func (o ApiSearchResponseComponentDetailDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSearchResponseComponentDetailDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aggregations) {
		toSerialize["aggregations"] = o.Aggregations
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableApiSearchResponseComponentDetailDocument struct {
	value *ApiSearchResponseComponentDetailDocument
	isSet bool
}

func (v NullableApiSearchResponseComponentDetailDocument) Get() *ApiSearchResponseComponentDetailDocument {
	return v.value
}

func (v *NullableApiSearchResponseComponentDetailDocument) Set(val *ApiSearchResponseComponentDetailDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSearchResponseComponentDetailDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSearchResponseComponentDetailDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSearchResponseComponentDetailDocument(val *ApiSearchResponseComponentDetailDocument) *NullableApiSearchResponseComponentDetailDocument {
	return &NullableApiSearchResponseComponentDetailDocument{value: val, isSet: true}
}

func (v NullableApiSearchResponseComponentDetailDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSearchResponseComponentDetailDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


