/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the PlanDTOv2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanDTOv2{}

// PlanDTOv2 struct for PlanDTOv2
type PlanDTOv2 struct {
	BillingPeriod *string `json:"billingPeriod,omitempty"`
	ChargebeeItemId *string `json:"chargebeeItemId,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	IsCurrentPlan *bool `json:"isCurrentPlan,omitempty"`
	MonthlyCredits *int32 `json:"monthlyCredits,omitempty"`
	PlanTier *string `json:"planTier,omitempty"`
	Price *float64 `json:"price,omitempty"`
}

// NewPlanDTOv2 instantiates a new PlanDTOv2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanDTOv2() *PlanDTOv2 {
	this := PlanDTOv2{}
	return &this
}

// NewPlanDTOv2WithDefaults instantiates a new PlanDTOv2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanDTOv2WithDefaults() *PlanDTOv2 {
	this := PlanDTOv2{}
	return &this
}

// GetBillingPeriod returns the BillingPeriod field value if set, zero value otherwise.
func (o *PlanDTOv2) GetBillingPeriod() string {
	if o == nil || IsNil(o.BillingPeriod) {
		var ret string
		return ret
	}
	return *o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetBillingPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.BillingPeriod) {
		return nil, false
	}
	return o.BillingPeriod, true
}

// HasBillingPeriod returns a boolean if a field has been set.
func (o *PlanDTOv2) HasBillingPeriod() bool {
	if o != nil && !IsNil(o.BillingPeriod) {
		return true
	}

	return false
}

// SetBillingPeriod gets a reference to the given string and assigns it to the BillingPeriod field.
func (o *PlanDTOv2) SetBillingPeriod(v string) {
	o.BillingPeriod = &v
}

// GetChargebeeItemId returns the ChargebeeItemId field value if set, zero value otherwise.
func (o *PlanDTOv2) GetChargebeeItemId() string {
	if o == nil || IsNil(o.ChargebeeItemId) {
		var ret string
		return ret
	}
	return *o.ChargebeeItemId
}

// GetChargebeeItemIdOk returns a tuple with the ChargebeeItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetChargebeeItemIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChargebeeItemId) {
		return nil, false
	}
	return o.ChargebeeItemId, true
}

// HasChargebeeItemId returns a boolean if a field has been set.
func (o *PlanDTOv2) HasChargebeeItemId() bool {
	if o != nil && !IsNil(o.ChargebeeItemId) {
		return true
	}

	return false
}

// SetChargebeeItemId gets a reference to the given string and assigns it to the ChargebeeItemId field.
func (o *PlanDTOv2) SetChargebeeItemId(v string) {
	o.ChargebeeItemId = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PlanDTOv2) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PlanDTOv2) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *PlanDTOv2) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetIsCurrentPlan returns the IsCurrentPlan field value if set, zero value otherwise.
func (o *PlanDTOv2) GetIsCurrentPlan() bool {
	if o == nil || IsNil(o.IsCurrentPlan) {
		var ret bool
		return ret
	}
	return *o.IsCurrentPlan
}

// GetIsCurrentPlanOk returns a tuple with the IsCurrentPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetIsCurrentPlanOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCurrentPlan) {
		return nil, false
	}
	return o.IsCurrentPlan, true
}

// HasIsCurrentPlan returns a boolean if a field has been set.
func (o *PlanDTOv2) HasIsCurrentPlan() bool {
	if o != nil && !IsNil(o.IsCurrentPlan) {
		return true
	}

	return false
}

// SetIsCurrentPlan gets a reference to the given bool and assigns it to the IsCurrentPlan field.
func (o *PlanDTOv2) SetIsCurrentPlan(v bool) {
	o.IsCurrentPlan = &v
}

// GetMonthlyCredits returns the MonthlyCredits field value if set, zero value otherwise.
func (o *PlanDTOv2) GetMonthlyCredits() int32 {
	if o == nil || IsNil(o.MonthlyCredits) {
		var ret int32
		return ret
	}
	return *o.MonthlyCredits
}

// GetMonthlyCreditsOk returns a tuple with the MonthlyCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetMonthlyCreditsOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyCredits) {
		return nil, false
	}
	return o.MonthlyCredits, true
}

// HasMonthlyCredits returns a boolean if a field has been set.
func (o *PlanDTOv2) HasMonthlyCredits() bool {
	if o != nil && !IsNil(o.MonthlyCredits) {
		return true
	}

	return false
}

// SetMonthlyCredits gets a reference to the given int32 and assigns it to the MonthlyCredits field.
func (o *PlanDTOv2) SetMonthlyCredits(v int32) {
	o.MonthlyCredits = &v
}

// GetPlanTier returns the PlanTier field value if set, zero value otherwise.
func (o *PlanDTOv2) GetPlanTier() string {
	if o == nil || IsNil(o.PlanTier) {
		var ret string
		return ret
	}
	return *o.PlanTier
}

// GetPlanTierOk returns a tuple with the PlanTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetPlanTierOk() (*string, bool) {
	if o == nil || IsNil(o.PlanTier) {
		return nil, false
	}
	return o.PlanTier, true
}

// HasPlanTier returns a boolean if a field has been set.
func (o *PlanDTOv2) HasPlanTier() bool {
	if o != nil && !IsNil(o.PlanTier) {
		return true
	}

	return false
}

// SetPlanTier gets a reference to the given string and assigns it to the PlanTier field.
func (o *PlanDTOv2) SetPlanTier(v string) {
	o.PlanTier = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PlanDTOv2) GetPrice() float64 {
	if o == nil || IsNil(o.Price) {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanDTOv2) GetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PlanDTOv2) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *PlanDTOv2) SetPrice(v float64) {
	o.Price = &v
}

func (o PlanDTOv2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanDTOv2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingPeriod) {
		toSerialize["billingPeriod"] = o.BillingPeriod
	}
	if !IsNil(o.ChargebeeItemId) {
		toSerialize["chargebeeItemId"] = o.ChargebeeItemId
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.IsCurrentPlan) {
		toSerialize["isCurrentPlan"] = o.IsCurrentPlan
	}
	if !IsNil(o.MonthlyCredits) {
		toSerialize["monthlyCredits"] = o.MonthlyCredits
	}
	if !IsNil(o.PlanTier) {
		toSerialize["planTier"] = o.PlanTier
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullablePlanDTOv2 struct {
	value *PlanDTOv2
	isSet bool
}

func (v NullablePlanDTOv2) Get() *PlanDTOv2 {
	return v.value
}

func (v *NullablePlanDTOv2) Set(val *PlanDTOv2) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanDTOv2) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanDTOv2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanDTOv2(val *PlanDTOv2) *NullablePlanDTOv2 {
	return &NullablePlanDTOv2{value: val, isSet: true}
}

func (v NullablePlanDTOv2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanDTOv2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


