/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the UsageDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageDTO{}

// UsageDTO struct for UsageDTO
type UsageDTO struct {
	CreditsTotal *int32 `json:"creditsTotal,omitempty"`
	CreditsUsed *int32 `json:"creditsUsed,omitempty"`
	CurrentPeriod *PeriodDTO `json:"currentPeriod,omitempty"`
}

// NewUsageDTO instantiates a new UsageDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageDTO() *UsageDTO {
	this := UsageDTO{}
	return &this
}

// NewUsageDTOWithDefaults instantiates a new UsageDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageDTOWithDefaults() *UsageDTO {
	this := UsageDTO{}
	return &this
}

// GetCreditsTotal returns the CreditsTotal field value if set, zero value otherwise.
func (o *UsageDTO) GetCreditsTotal() int32 {
	if o == nil || IsNil(o.CreditsTotal) {
		var ret int32
		return ret
	}
	return *o.CreditsTotal
}

// GetCreditsTotalOk returns a tuple with the CreditsTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDTO) GetCreditsTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsTotal) {
		return nil, false
	}
	return o.CreditsTotal, true
}

// HasCreditsTotal returns a boolean if a field has been set.
func (o *UsageDTO) HasCreditsTotal() bool {
	if o != nil && !IsNil(o.CreditsTotal) {
		return true
	}

	return false
}

// SetCreditsTotal gets a reference to the given int32 and assigns it to the CreditsTotal field.
func (o *UsageDTO) SetCreditsTotal(v int32) {
	o.CreditsTotal = &v
}

// GetCreditsUsed returns the CreditsUsed field value if set, zero value otherwise.
func (o *UsageDTO) GetCreditsUsed() int32 {
	if o == nil || IsNil(o.CreditsUsed) {
		var ret int32
		return ret
	}
	return *o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDTO) GetCreditsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsUsed) {
		return nil, false
	}
	return o.CreditsUsed, true
}

// HasCreditsUsed returns a boolean if a field has been set.
func (o *UsageDTO) HasCreditsUsed() bool {
	if o != nil && !IsNil(o.CreditsUsed) {
		return true
	}

	return false
}

// SetCreditsUsed gets a reference to the given int32 and assigns it to the CreditsUsed field.
func (o *UsageDTO) SetCreditsUsed(v int32) {
	o.CreditsUsed = &v
}

// GetCurrentPeriod returns the CurrentPeriod field value if set, zero value otherwise.
func (o *UsageDTO) GetCurrentPeriod() PeriodDTO {
	if o == nil || IsNil(o.CurrentPeriod) {
		var ret PeriodDTO
		return ret
	}
	return *o.CurrentPeriod
}

// GetCurrentPeriodOk returns a tuple with the CurrentPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDTO) GetCurrentPeriodOk() (*PeriodDTO, bool) {
	if o == nil || IsNil(o.CurrentPeriod) {
		return nil, false
	}
	return o.CurrentPeriod, true
}

// HasCurrentPeriod returns a boolean if a field has been set.
func (o *UsageDTO) HasCurrentPeriod() bool {
	if o != nil && !IsNil(o.CurrentPeriod) {
		return true
	}

	return false
}

// SetCurrentPeriod gets a reference to the given PeriodDTO and assigns it to the CurrentPeriod field.
func (o *UsageDTO) SetCurrentPeriod(v PeriodDTO) {
	o.CurrentPeriod = &v
}

func (o UsageDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreditsTotal) {
		toSerialize["creditsTotal"] = o.CreditsTotal
	}
	if !IsNil(o.CreditsUsed) {
		toSerialize["creditsUsed"] = o.CreditsUsed
	}
	if !IsNil(o.CurrentPeriod) {
		toSerialize["currentPeriod"] = o.CurrentPeriod
	}
	return toSerialize, nil
}

type NullableUsageDTO struct {
	value *UsageDTO
	isSet bool
}

func (v NullableUsageDTO) Get() *UsageDTO {
	return v.value
}

func (v *NullableUsageDTO) Set(val *UsageDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageDTO(val *UsageDTO) *NullableUsageDTO {
	return &NullableUsageDTO{value: val, isSet: true}
}

func (v NullableUsageDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


