/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the OrganizationBillingDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationBillingDTO{}

// OrganizationBillingDTO struct for OrganizationBillingDTO
type OrganizationBillingDTO struct {
	MonthlyCost *float64 `json:"monthlyCost,omitempty"`
	NextBilling *string `json:"nextBilling,omitempty"`
	PaymentMethod *string `json:"paymentMethod,omitempty"`
}

// NewOrganizationBillingDTO instantiates a new OrganizationBillingDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationBillingDTO() *OrganizationBillingDTO {
	this := OrganizationBillingDTO{}
	return &this
}

// NewOrganizationBillingDTOWithDefaults instantiates a new OrganizationBillingDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationBillingDTOWithDefaults() *OrganizationBillingDTO {
	this := OrganizationBillingDTO{}
	return &this
}

// GetMonthlyCost returns the MonthlyCost field value if set, zero value otherwise.
func (o *OrganizationBillingDTO) GetMonthlyCost() float64 {
	if o == nil || IsNil(o.MonthlyCost) {
		var ret float64
		return ret
	}
	return *o.MonthlyCost
}

// GetMonthlyCostOk returns a tuple with the MonthlyCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationBillingDTO) GetMonthlyCostOk() (*float64, bool) {
	if o == nil || IsNil(o.MonthlyCost) {
		return nil, false
	}
	return o.MonthlyCost, true
}

// HasMonthlyCost returns a boolean if a field has been set.
func (o *OrganizationBillingDTO) HasMonthlyCost() bool {
	if o != nil && !IsNil(o.MonthlyCost) {
		return true
	}

	return false
}

// SetMonthlyCost gets a reference to the given float64 and assigns it to the MonthlyCost field.
func (o *OrganizationBillingDTO) SetMonthlyCost(v float64) {
	o.MonthlyCost = &v
}

// GetNextBilling returns the NextBilling field value if set, zero value otherwise.
func (o *OrganizationBillingDTO) GetNextBilling() string {
	if o == nil || IsNil(o.NextBilling) {
		var ret string
		return ret
	}
	return *o.NextBilling
}

// GetNextBillingOk returns a tuple with the NextBilling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationBillingDTO) GetNextBillingOk() (*string, bool) {
	if o == nil || IsNil(o.NextBilling) {
		return nil, false
	}
	return o.NextBilling, true
}

// HasNextBilling returns a boolean if a field has been set.
func (o *OrganizationBillingDTO) HasNextBilling() bool {
	if o != nil && !IsNil(o.NextBilling) {
		return true
	}

	return false
}

// SetNextBilling gets a reference to the given string and assigns it to the NextBilling field.
func (o *OrganizationBillingDTO) SetNextBilling(v string) {
	o.NextBilling = &v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *OrganizationBillingDTO) GetPaymentMethod() string {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret string
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationBillingDTO) GetPaymentMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *OrganizationBillingDTO) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given string and assigns it to the PaymentMethod field.
func (o *OrganizationBillingDTO) SetPaymentMethod(v string) {
	o.PaymentMethod = &v
}

func (o OrganizationBillingDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationBillingDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MonthlyCost) {
		toSerialize["monthlyCost"] = o.MonthlyCost
	}
	if !IsNil(o.NextBilling) {
		toSerialize["nextBilling"] = o.NextBilling
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["paymentMethod"] = o.PaymentMethod
	}
	return toSerialize, nil
}

type NullableOrganizationBillingDTO struct {
	value *OrganizationBillingDTO
	isSet bool
}

func (v NullableOrganizationBillingDTO) Get() *OrganizationBillingDTO {
	return v.value
}

func (v *NullableOrganizationBillingDTO) Set(val *OrganizationBillingDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationBillingDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationBillingDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationBillingDTO(val *OrganizationBillingDTO) *NullableOrganizationBillingDTO {
	return &NullableOrganizationBillingDTO{value: val, isSet: true}
}

func (v NullableOrganizationBillingDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationBillingDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


