/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202608
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the GovernanceWriteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GovernanceWriteResponse{}

// GovernanceWriteResponse struct for GovernanceWriteResponse
type GovernanceWriteResponse struct {
	ConfigVersion *int64 `json:"configVersion,omitempty"`
}

// NewGovernanceWriteResponse instantiates a new GovernanceWriteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovernanceWriteResponse() *GovernanceWriteResponse {
	this := GovernanceWriteResponse{}
	return &this
}

// NewGovernanceWriteResponseWithDefaults instantiates a new GovernanceWriteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovernanceWriteResponseWithDefaults() *GovernanceWriteResponse {
	this := GovernanceWriteResponse{}
	return &this
}

// GetConfigVersion returns the ConfigVersion field value if set, zero value otherwise.
func (o *GovernanceWriteResponse) GetConfigVersion() int64 {
	if o == nil || IsNil(o.ConfigVersion) {
		var ret int64
		return ret
	}
	return *o.ConfigVersion
}

// GetConfigVersionOk returns a tuple with the ConfigVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GovernanceWriteResponse) GetConfigVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.ConfigVersion) {
		return nil, false
	}
	return o.ConfigVersion, true
}

// HasConfigVersion returns a boolean if a field has been set.
func (o *GovernanceWriteResponse) HasConfigVersion() bool {
	if o != nil && !IsNil(o.ConfigVersion) {
		return true
	}

	return false
}

// SetConfigVersion gets a reference to the given int64 and assigns it to the ConfigVersion field.
func (o *GovernanceWriteResponse) SetConfigVersion(v int64) {
	o.ConfigVersion = &v
}

func (o GovernanceWriteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GovernanceWriteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigVersion) {
		toSerialize["configVersion"] = o.ConfigVersion
	}
	return toSerialize, nil
}

type NullableGovernanceWriteResponse struct {
	value *GovernanceWriteResponse
	isSet bool
}

func (v NullableGovernanceWriteResponse) Get() *GovernanceWriteResponse {
	return v.value
}

func (v *NullableGovernanceWriteResponse) Set(val *GovernanceWriteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGovernanceWriteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGovernanceWriteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovernanceWriteResponse(val *GovernanceWriteResponse) *NullableGovernanceWriteResponse {
	return &NullableGovernanceWriteResponse{value: val, isSet: true}
}

func (v NullableGovernanceWriteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovernanceWriteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


