/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the SubscriptionDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionDetailsResponse{}

// SubscriptionDetailsResponse struct for SubscriptionDetailsResponse
type SubscriptionDetailsResponse struct {
	CreditUsage *CreditUsage `json:"creditUsage,omitempty"`
	Plan *Plan `json:"plan,omitempty"`
}

// NewSubscriptionDetailsResponse instantiates a new SubscriptionDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionDetailsResponse() *SubscriptionDetailsResponse {
	this := SubscriptionDetailsResponse{}
	return &this
}

// NewSubscriptionDetailsResponseWithDefaults instantiates a new SubscriptionDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionDetailsResponseWithDefaults() *SubscriptionDetailsResponse {
	this := SubscriptionDetailsResponse{}
	return &this
}

// GetCreditUsage returns the CreditUsage field value if set, zero value otherwise.
func (o *SubscriptionDetailsResponse) GetCreditUsage() CreditUsage {
	if o == nil || IsNil(o.CreditUsage) {
		var ret CreditUsage
		return ret
	}
	return *o.CreditUsage
}

// GetCreditUsageOk returns a tuple with the CreditUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionDetailsResponse) GetCreditUsageOk() (*CreditUsage, bool) {
	if o == nil || IsNil(o.CreditUsage) {
		return nil, false
	}
	return o.CreditUsage, true
}

// HasCreditUsage returns a boolean if a field has been set.
func (o *SubscriptionDetailsResponse) HasCreditUsage() bool {
	if o != nil && !IsNil(o.CreditUsage) {
		return true
	}

	return false
}

// SetCreditUsage gets a reference to the given CreditUsage and assigns it to the CreditUsage field.
func (o *SubscriptionDetailsResponse) SetCreditUsage(v CreditUsage) {
	o.CreditUsage = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *SubscriptionDetailsResponse) GetPlan() Plan {
	if o == nil || IsNil(o.Plan) {
		var ret Plan
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionDetailsResponse) GetPlanOk() (*Plan, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *SubscriptionDetailsResponse) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given Plan and assigns it to the Plan field.
func (o *SubscriptionDetailsResponse) SetPlan(v Plan) {
	o.Plan = &v
}

func (o SubscriptionDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreditUsage) {
		toSerialize["creditUsage"] = o.CreditUsage
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	return toSerialize, nil
}

type NullableSubscriptionDetailsResponse struct {
	value *SubscriptionDetailsResponse
	isSet bool
}

func (v NullableSubscriptionDetailsResponse) Get() *SubscriptionDetailsResponse {
	return v.value
}

func (v *NullableSubscriptionDetailsResponse) Set(val *SubscriptionDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionDetailsResponse(val *SubscriptionDetailsResponse) *NullableSubscriptionDetailsResponse {
	return &NullableSubscriptionDetailsResponse{value: val, isSet: true}
}

func (v NullableSubscriptionDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


