/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the DashboardRowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardRowResponse{}

// DashboardRowResponse struct for DashboardRowResponse
type DashboardRowResponse struct {
	Archived *bool `json:"archived,omitempty"`
	InstallationRepoId *int64 `json:"installationRepoId,omitempty"`
	LastRunAt *string `json:"lastRunAt,omitempty"`
	LastRunStatus *string `json:"lastRunStatus,omitempty"`
	RepoFullName *string `json:"repoFullName,omitempty"`
	RepoId *int64 `json:"repoId,omitempty"`
	RunCount *int32 `json:"runCount,omitempty"`
	SetupPrUrl *string `json:"setupPrUrl,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusLabel *string `json:"statusLabel,omitempty"`
	WorkflowPresent *bool `json:"workflowPresent,omitempty"`
}

// NewDashboardRowResponse instantiates a new DashboardRowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardRowResponse() *DashboardRowResponse {
	this := DashboardRowResponse{}
	return &this
}

// NewDashboardRowResponseWithDefaults instantiates a new DashboardRowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardRowResponseWithDefaults() *DashboardRowResponse {
	this := DashboardRowResponse{}
	return &this
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *DashboardRowResponse) SetArchived(v bool) {
	o.Archived = &v
}

// GetInstallationRepoId returns the InstallationRepoId field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetInstallationRepoId() int64 {
	if o == nil || IsNil(o.InstallationRepoId) {
		var ret int64
		return ret
	}
	return *o.InstallationRepoId
}

// GetInstallationRepoIdOk returns a tuple with the InstallationRepoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetInstallationRepoIdOk() (*int64, bool) {
	if o == nil || IsNil(o.InstallationRepoId) {
		return nil, false
	}
	return o.InstallationRepoId, true
}

// HasInstallationRepoId returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasInstallationRepoId() bool {
	if o != nil && !IsNil(o.InstallationRepoId) {
		return true
	}

	return false
}

// SetInstallationRepoId gets a reference to the given int64 and assigns it to the InstallationRepoId field.
func (o *DashboardRowResponse) SetInstallationRepoId(v int64) {
	o.InstallationRepoId = &v
}

// GetLastRunAt returns the LastRunAt field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetLastRunAt() string {
	if o == nil || IsNil(o.LastRunAt) {
		var ret string
		return ret
	}
	return *o.LastRunAt
}

// GetLastRunAtOk returns a tuple with the LastRunAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetLastRunAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastRunAt) {
		return nil, false
	}
	return o.LastRunAt, true
}

// HasLastRunAt returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasLastRunAt() bool {
	if o != nil && !IsNil(o.LastRunAt) {
		return true
	}

	return false
}

// SetLastRunAt gets a reference to the given string and assigns it to the LastRunAt field.
func (o *DashboardRowResponse) SetLastRunAt(v string) {
	o.LastRunAt = &v
}

// GetLastRunStatus returns the LastRunStatus field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetLastRunStatus() string {
	if o == nil || IsNil(o.LastRunStatus) {
		var ret string
		return ret
	}
	return *o.LastRunStatus
}

// GetLastRunStatusOk returns a tuple with the LastRunStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetLastRunStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LastRunStatus) {
		return nil, false
	}
	return o.LastRunStatus, true
}

// HasLastRunStatus returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasLastRunStatus() bool {
	if o != nil && !IsNil(o.LastRunStatus) {
		return true
	}

	return false
}

// SetLastRunStatus gets a reference to the given string and assigns it to the LastRunStatus field.
func (o *DashboardRowResponse) SetLastRunStatus(v string) {
	o.LastRunStatus = &v
}

// GetRepoFullName returns the RepoFullName field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetRepoFullName() string {
	if o == nil || IsNil(o.RepoFullName) {
		var ret string
		return ret
	}
	return *o.RepoFullName
}

// GetRepoFullNameOk returns a tuple with the RepoFullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetRepoFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.RepoFullName) {
		return nil, false
	}
	return o.RepoFullName, true
}

// HasRepoFullName returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasRepoFullName() bool {
	if o != nil && !IsNil(o.RepoFullName) {
		return true
	}

	return false
}

// SetRepoFullName gets a reference to the given string and assigns it to the RepoFullName field.
func (o *DashboardRowResponse) SetRepoFullName(v string) {
	o.RepoFullName = &v
}

// GetRepoId returns the RepoId field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetRepoId() int64 {
	if o == nil || IsNil(o.RepoId) {
		var ret int64
		return ret
	}
	return *o.RepoId
}

// GetRepoIdOk returns a tuple with the RepoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetRepoIdOk() (*int64, bool) {
	if o == nil || IsNil(o.RepoId) {
		return nil, false
	}
	return o.RepoId, true
}

// HasRepoId returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasRepoId() bool {
	if o != nil && !IsNil(o.RepoId) {
		return true
	}

	return false
}

// SetRepoId gets a reference to the given int64 and assigns it to the RepoId field.
func (o *DashboardRowResponse) SetRepoId(v int64) {
	o.RepoId = &v
}

// GetRunCount returns the RunCount field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetRunCount() int32 {
	if o == nil || IsNil(o.RunCount) {
		var ret int32
		return ret
	}
	return *o.RunCount
}

// GetRunCountOk returns a tuple with the RunCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetRunCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RunCount) {
		return nil, false
	}
	return o.RunCount, true
}

// HasRunCount returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasRunCount() bool {
	if o != nil && !IsNil(o.RunCount) {
		return true
	}

	return false
}

// SetRunCount gets a reference to the given int32 and assigns it to the RunCount field.
func (o *DashboardRowResponse) SetRunCount(v int32) {
	o.RunCount = &v
}

// GetSetupPrUrl returns the SetupPrUrl field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetSetupPrUrl() string {
	if o == nil || IsNil(o.SetupPrUrl) {
		var ret string
		return ret
	}
	return *o.SetupPrUrl
}

// GetSetupPrUrlOk returns a tuple with the SetupPrUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetSetupPrUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SetupPrUrl) {
		return nil, false
	}
	return o.SetupPrUrl, true
}

// HasSetupPrUrl returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasSetupPrUrl() bool {
	if o != nil && !IsNil(o.SetupPrUrl) {
		return true
	}

	return false
}

// SetSetupPrUrl gets a reference to the given string and assigns it to the SetupPrUrl field.
func (o *DashboardRowResponse) SetSetupPrUrl(v string) {
	o.SetupPrUrl = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DashboardRowResponse) SetStatus(v string) {
	o.Status = &v
}

// GetStatusLabel returns the StatusLabel field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetStatusLabel() string {
	if o == nil || IsNil(o.StatusLabel) {
		var ret string
		return ret
	}
	return *o.StatusLabel
}

// GetStatusLabelOk returns a tuple with the StatusLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetStatusLabelOk() (*string, bool) {
	if o == nil || IsNil(o.StatusLabel) {
		return nil, false
	}
	return o.StatusLabel, true
}

// HasStatusLabel returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasStatusLabel() bool {
	if o != nil && !IsNil(o.StatusLabel) {
		return true
	}

	return false
}

// SetStatusLabel gets a reference to the given string and assigns it to the StatusLabel field.
func (o *DashboardRowResponse) SetStatusLabel(v string) {
	o.StatusLabel = &v
}

// GetWorkflowPresent returns the WorkflowPresent field value if set, zero value otherwise.
func (o *DashboardRowResponse) GetWorkflowPresent() bool {
	if o == nil || IsNil(o.WorkflowPresent) {
		var ret bool
		return ret
	}
	return *o.WorkflowPresent
}

// GetWorkflowPresentOk returns a tuple with the WorkflowPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardRowResponse) GetWorkflowPresentOk() (*bool, bool) {
	if o == nil || IsNil(o.WorkflowPresent) {
		return nil, false
	}
	return o.WorkflowPresent, true
}

// HasWorkflowPresent returns a boolean if a field has been set.
func (o *DashboardRowResponse) HasWorkflowPresent() bool {
	if o != nil && !IsNil(o.WorkflowPresent) {
		return true
	}

	return false
}

// SetWorkflowPresent gets a reference to the given bool and assigns it to the WorkflowPresent field.
func (o *DashboardRowResponse) SetWorkflowPresent(v bool) {
	o.WorkflowPresent = &v
}

func (o DashboardRowResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardRowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.InstallationRepoId) {
		toSerialize["installationRepoId"] = o.InstallationRepoId
	}
	if !IsNil(o.LastRunAt) {
		toSerialize["lastRunAt"] = o.LastRunAt
	}
	if !IsNil(o.LastRunStatus) {
		toSerialize["lastRunStatus"] = o.LastRunStatus
	}
	if !IsNil(o.RepoFullName) {
		toSerialize["repoFullName"] = o.RepoFullName
	}
	if !IsNil(o.RepoId) {
		toSerialize["repoId"] = o.RepoId
	}
	if !IsNil(o.RunCount) {
		toSerialize["runCount"] = o.RunCount
	}
	if !IsNil(o.SetupPrUrl) {
		toSerialize["setupPrUrl"] = o.SetupPrUrl
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusLabel) {
		toSerialize["statusLabel"] = o.StatusLabel
	}
	if !IsNil(o.WorkflowPresent) {
		toSerialize["workflowPresent"] = o.WorkflowPresent
	}
	return toSerialize, nil
}

type NullableDashboardRowResponse struct {
	value *DashboardRowResponse
	isSet bool
}

func (v NullableDashboardRowResponse) Get() *DashboardRowResponse {
	return v.value
}

func (v *NullableDashboardRowResponse) Set(val *DashboardRowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardRowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardRowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardRowResponse(val *DashboardRowResponse) *NullableDashboardRowResponse {
	return &NullableDashboardRowResponse{value: val, isSet: true}
}

func (v NullableDashboardRowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardRowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


