/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateTokenRequest{}

// RotateTokenRequest struct for RotateTokenRequest
type RotateTokenRequest struct {
	DaysUntilExpiration int32 `json:"daysUntilExpiration"`
	Name string `json:"name"`
}

type _RotateTokenRequest RotateTokenRequest

// NewRotateTokenRequest instantiates a new RotateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateTokenRequest(daysUntilExpiration int32, name string) *RotateTokenRequest {
	this := RotateTokenRequest{}
	this.DaysUntilExpiration = daysUntilExpiration
	this.Name = name
	return &this
}

// NewRotateTokenRequestWithDefaults instantiates a new RotateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateTokenRequestWithDefaults() *RotateTokenRequest {
	this := RotateTokenRequest{}
	return &this
}

// GetDaysUntilExpiration returns the DaysUntilExpiration field value
func (o *RotateTokenRequest) GetDaysUntilExpiration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DaysUntilExpiration
}

// GetDaysUntilExpirationOk returns a tuple with the DaysUntilExpiration field value
// and a boolean to check if the value has been set.
func (o *RotateTokenRequest) GetDaysUntilExpirationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DaysUntilExpiration, true
}

// SetDaysUntilExpiration sets field value
func (o *RotateTokenRequest) SetDaysUntilExpiration(v int32) {
	o.DaysUntilExpiration = v
}

// GetName returns the Name field value
func (o *RotateTokenRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RotateTokenRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RotateTokenRequest) SetName(v string) {
	o.Name = v
}

func (o RotateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["daysUntilExpiration"] = o.DaysUntilExpiration
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *RotateTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"daysUntilExpiration",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateTokenRequest := _RotateTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateTokenRequest)

	if err != nil {
		return err
	}

	*o = RotateTokenRequest(varRotateTokenRequest)

	return err
}

type NullableRotateTokenRequest struct {
	value *RotateTokenRequest
	isSet bool
}

func (v NullableRotateTokenRequest) Get() *RotateTokenRequest {
	return v.value
}

func (v *NullableRotateTokenRequest) Set(val *RotateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateTokenRequest(val *RotateTokenRequest) *NullableRotateTokenRequest {
	return &NullableRotateTokenRequest{value: val, isSet: true}
}

func (v NullableRotateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


