/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202606
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the PeriodDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeriodDTO{}

// PeriodDTO struct for PeriodDTO
type PeriodDTO struct {
	End *string `json:"end,omitempty"`
	Start *string `json:"start,omitempty"`
}

// NewPeriodDTO instantiates a new PeriodDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeriodDTO() *PeriodDTO {
	this := PeriodDTO{}
	return &this
}

// NewPeriodDTOWithDefaults instantiates a new PeriodDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeriodDTOWithDefaults() *PeriodDTO {
	this := PeriodDTO{}
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *PeriodDTO) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeriodDTO) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *PeriodDTO) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *PeriodDTO) SetEnd(v string) {
	o.End = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *PeriodDTO) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeriodDTO) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *PeriodDTO) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *PeriodDTO) SetStart(v string) {
	o.Start = &v
}

func (o PeriodDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeriodDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	return toSerialize, nil
}

type NullablePeriodDTO struct {
	value *PeriodDTO
	isSet bool
}

func (v NullablePeriodDTO) Get() *PeriodDTO {
	return v.value
}

func (v *NullablePeriodDTO) Set(val *PeriodDTO) {
	v.value = val
	v.isSet = true
}

func (v NullablePeriodDTO) IsSet() bool {
	return v.isSet
}

func (v *NullablePeriodDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeriodDTO(val *PeriodDTO) *NullablePeriodDTO {
	return &NullablePeriodDTO{value: val, isSet: true}
}

func (v NullablePeriodDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeriodDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


