/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202606
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the AffectedComponentVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffectedComponentVersion{}

// AffectedComponentVersion struct for AffectedComponentVersion
type AffectedComponentVersion struct {
	Ecosystem *string `json:"ecosystem,omitempty"`
	FullPackageName *string `json:"fullPackageName,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	PackageName *string `json:"packageName,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewAffectedComponentVersion instantiates a new AffectedComponentVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffectedComponentVersion() *AffectedComponentVersion {
	this := AffectedComponentVersion{}
	return &this
}

// NewAffectedComponentVersionWithDefaults instantiates a new AffectedComponentVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffectedComponentVersionWithDefaults() *AffectedComponentVersion {
	this := AffectedComponentVersion{}
	return &this
}

// GetEcosystem returns the Ecosystem field value if set, zero value otherwise.
func (o *AffectedComponentVersion) GetEcosystem() string {
	if o == nil || IsNil(o.Ecosystem) {
		var ret string
		return ret
	}
	return *o.Ecosystem
}

// GetEcosystemOk returns a tuple with the Ecosystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffectedComponentVersion) GetEcosystemOk() (*string, bool) {
	if o == nil || IsNil(o.Ecosystem) {
		return nil, false
	}
	return o.Ecosystem, true
}

// HasEcosystem returns a boolean if a field has been set.
func (o *AffectedComponentVersion) HasEcosystem() bool {
	if o != nil && !IsNil(o.Ecosystem) {
		return true
	}

	return false
}

// SetEcosystem gets a reference to the given string and assigns it to the Ecosystem field.
func (o *AffectedComponentVersion) SetEcosystem(v string) {
	o.Ecosystem = &v
}

// GetFullPackageName returns the FullPackageName field value if set, zero value otherwise.
func (o *AffectedComponentVersion) GetFullPackageName() string {
	if o == nil || IsNil(o.FullPackageName) {
		var ret string
		return ret
	}
	return *o.FullPackageName
}

// GetFullPackageNameOk returns a tuple with the FullPackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffectedComponentVersion) GetFullPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullPackageName) {
		return nil, false
	}
	return o.FullPackageName, true
}

// HasFullPackageName returns a boolean if a field has been set.
func (o *AffectedComponentVersion) HasFullPackageName() bool {
	if o != nil && !IsNil(o.FullPackageName) {
		return true
	}

	return false
}

// SetFullPackageName gets a reference to the given string and assigns it to the FullPackageName field.
func (o *AffectedComponentVersion) SetFullPackageName(v string) {
	o.FullPackageName = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AffectedComponentVersion) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffectedComponentVersion) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AffectedComponentVersion) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AffectedComponentVersion) SetNamespace(v string) {
	o.Namespace = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *AffectedComponentVersion) GetPackageName() string {
	if o == nil || IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffectedComponentVersion) GetPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *AffectedComponentVersion) HasPackageName() bool {
	if o != nil && !IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *AffectedComponentVersion) SetPackageName(v string) {
	o.PackageName = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AffectedComponentVersion) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffectedComponentVersion) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AffectedComponentVersion) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *AffectedComponentVersion) SetVersion(v string) {
	o.Version = &v
}

func (o AffectedComponentVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffectedComponentVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ecosystem) {
		toSerialize["ecosystem"] = o.Ecosystem
	}
	if !IsNil(o.FullPackageName) {
		toSerialize["fullPackageName"] = o.FullPackageName
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.PackageName) {
		toSerialize["packageName"] = o.PackageName
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableAffectedComponentVersion struct {
	value *AffectedComponentVersion
	isSet bool
}

func (v NullableAffectedComponentVersion) Get() *AffectedComponentVersion {
	return v.value
}

func (v *NullableAffectedComponentVersion) Set(val *AffectedComponentVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableAffectedComponentVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableAffectedComponentVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffectedComponentVersion(val *AffectedComponentVersion) *NullableAffectedComponentVersion {
	return &NullableAffectedComponentVersion{value: val, isSet: true}
}

func (v NullableAffectedComponentVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffectedComponentVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


