/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the OrgOnboardingActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgOnboardingActivity{}

// OrgOnboardingActivity struct for OrgOnboardingActivity
type OrgOnboardingActivity struct {
	OthersOnboarding *bool `json:"othersOnboarding,omitempty"`
}

// NewOrgOnboardingActivity instantiates a new OrgOnboardingActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgOnboardingActivity() *OrgOnboardingActivity {
	this := OrgOnboardingActivity{}
	return &this
}

// NewOrgOnboardingActivityWithDefaults instantiates a new OrgOnboardingActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgOnboardingActivityWithDefaults() *OrgOnboardingActivity {
	this := OrgOnboardingActivity{}
	return &this
}

// GetOthersOnboarding returns the OthersOnboarding field value if set, zero value otherwise.
func (o *OrgOnboardingActivity) GetOthersOnboarding() bool {
	if o == nil || IsNil(o.OthersOnboarding) {
		var ret bool
		return ret
	}
	return *o.OthersOnboarding
}

// GetOthersOnboardingOk returns a tuple with the OthersOnboarding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOnboardingActivity) GetOthersOnboardingOk() (*bool, bool) {
	if o == nil || IsNil(o.OthersOnboarding) {
		return nil, false
	}
	return o.OthersOnboarding, true
}

// HasOthersOnboarding returns a boolean if a field has been set.
func (o *OrgOnboardingActivity) HasOthersOnboarding() bool {
	if o != nil && !IsNil(o.OthersOnboarding) {
		return true
	}

	return false
}

// SetOthersOnboarding gets a reference to the given bool and assigns it to the OthersOnboarding field.
func (o *OrgOnboardingActivity) SetOthersOnboarding(v bool) {
	o.OthersOnboarding = &v
}

func (o OrgOnboardingActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgOnboardingActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OthersOnboarding) {
		toSerialize["othersOnboarding"] = o.OthersOnboarding
	}
	return toSerialize, nil
}

type NullableOrgOnboardingActivity struct {
	value *OrgOnboardingActivity
	isSet bool
}

func (v NullableOrgOnboardingActivity) Get() *OrgOnboardingActivity {
	return v.value
}

func (v *NullableOrgOnboardingActivity) Set(val *OrgOnboardingActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgOnboardingActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgOnboardingActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgOnboardingActivity(val *OrgOnboardingActivity) *NullableOrgOnboardingActivity {
	return &NullableOrgOnboardingActivity{value: val, isSet: true}
}

func (v NullableOrgOnboardingActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgOnboardingActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


