/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the BulkOnboardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkOnboardResponse{}

// BulkOnboardResponse struct for BulkOnboardResponse
type BulkOnboardResponse struct {
	JobId *int64 `json:"jobId,omitempty"`
}

// NewBulkOnboardResponse instantiates a new BulkOnboardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkOnboardResponse() *BulkOnboardResponse {
	this := BulkOnboardResponse{}
	return &this
}

// NewBulkOnboardResponseWithDefaults instantiates a new BulkOnboardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkOnboardResponseWithDefaults() *BulkOnboardResponse {
	this := BulkOnboardResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *BulkOnboardResponse) GetJobId() int64 {
	if o == nil || IsNil(o.JobId) {
		var ret int64
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkOnboardResponse) GetJobIdOk() (*int64, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *BulkOnboardResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given int64 and assigns it to the JobId field.
func (o *BulkOnboardResponse) SetJobId(v int64) {
	o.JobId = &v
}

func (o BulkOnboardResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkOnboardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	return toSerialize, nil
}

type NullableBulkOnboardResponse struct {
	value *BulkOnboardResponse
	isSet bool
}

func (v NullableBulkOnboardResponse) Get() *BulkOnboardResponse {
	return v.value
}

func (v *NullableBulkOnboardResponse) Set(val *BulkOnboardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkOnboardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkOnboardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkOnboardResponse(val *BulkOnboardResponse) *NullableBulkOnboardResponse {
	return &NullableBulkOnboardResponse{value: val, isSet: true}
}

func (v NullableBulkOnboardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkOnboardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


