/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the DailyCreditUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyCreditUsage{}

// DailyCreditUsage struct for DailyCreditUsage
type DailyCreditUsage struct {
	CumulativeUsage *float32 `json:"cumulativeUsage,omitempty"`
	DailyUsage *float32 `json:"dailyUsage,omitempty"`
	Date *string `json:"date,omitempty"`
}

// NewDailyCreditUsage instantiates a new DailyCreditUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyCreditUsage() *DailyCreditUsage {
	this := DailyCreditUsage{}
	return &this
}

// NewDailyCreditUsageWithDefaults instantiates a new DailyCreditUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyCreditUsageWithDefaults() *DailyCreditUsage {
	this := DailyCreditUsage{}
	return &this
}

// GetCumulativeUsage returns the CumulativeUsage field value if set, zero value otherwise.
func (o *DailyCreditUsage) GetCumulativeUsage() float32 {
	if o == nil || IsNil(o.CumulativeUsage) {
		var ret float32
		return ret
	}
	return *o.CumulativeUsage
}

// GetCumulativeUsageOk returns a tuple with the CumulativeUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyCreditUsage) GetCumulativeUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.CumulativeUsage) {
		return nil, false
	}
	return o.CumulativeUsage, true
}

// HasCumulativeUsage returns a boolean if a field has been set.
func (o *DailyCreditUsage) HasCumulativeUsage() bool {
	if o != nil && !IsNil(o.CumulativeUsage) {
		return true
	}

	return false
}

// SetCumulativeUsage gets a reference to the given float32 and assigns it to the CumulativeUsage field.
func (o *DailyCreditUsage) SetCumulativeUsage(v float32) {
	o.CumulativeUsage = &v
}

// GetDailyUsage returns the DailyUsage field value if set, zero value otherwise.
func (o *DailyCreditUsage) GetDailyUsage() float32 {
	if o == nil || IsNil(o.DailyUsage) {
		var ret float32
		return ret
	}
	return *o.DailyUsage
}

// GetDailyUsageOk returns a tuple with the DailyUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyCreditUsage) GetDailyUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.DailyUsage) {
		return nil, false
	}
	return o.DailyUsage, true
}

// HasDailyUsage returns a boolean if a field has been set.
func (o *DailyCreditUsage) HasDailyUsage() bool {
	if o != nil && !IsNil(o.DailyUsage) {
		return true
	}

	return false
}

// SetDailyUsage gets a reference to the given float32 and assigns it to the DailyUsage field.
func (o *DailyCreditUsage) SetDailyUsage(v float32) {
	o.DailyUsage = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *DailyCreditUsage) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyCreditUsage) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *DailyCreditUsage) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *DailyCreditUsage) SetDate(v string) {
	o.Date = &v
}

func (o DailyCreditUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyCreditUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CumulativeUsage) {
		toSerialize["cumulativeUsage"] = o.CumulativeUsage
	}
	if !IsNil(o.DailyUsage) {
		toSerialize["dailyUsage"] = o.DailyUsage
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	return toSerialize, nil
}

type NullableDailyCreditUsage struct {
	value *DailyCreditUsage
	isSet bool
}

func (v NullableDailyCreditUsage) Get() *DailyCreditUsage {
	return v.value
}

func (v *NullableDailyCreditUsage) Set(val *DailyCreditUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyCreditUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyCreditUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyCreditUsage(val *DailyCreditUsage) *NullableDailyCreditUsage {
	return &NullableDailyCreditUsage{value: val, isSet: true}
}

func (v NullableDailyCreditUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyCreditUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


