/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202605
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the VulnerableMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VulnerableMethod{}

// VulnerableMethod struct for VulnerableMethod
type VulnerableMethod struct {
	Signature *string `json:"signature,omitempty"`
	Type *string `json:"type,omitempty"`
	VulnerableParameters []int32 `json:"vulnerableParameters,omitempty"`
}

// NewVulnerableMethod instantiates a new VulnerableMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVulnerableMethod() *VulnerableMethod {
	this := VulnerableMethod{}
	return &this
}

// NewVulnerableMethodWithDefaults instantiates a new VulnerableMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVulnerableMethodWithDefaults() *VulnerableMethod {
	this := VulnerableMethod{}
	return &this
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *VulnerableMethod) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VulnerableMethod) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *VulnerableMethod) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *VulnerableMethod) SetSignature(v string) {
	o.Signature = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *VulnerableMethod) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VulnerableMethod) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *VulnerableMethod) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *VulnerableMethod) SetType(v string) {
	o.Type = &v
}

// GetVulnerableParameters returns the VulnerableParameters field value if set, zero value otherwise.
func (o *VulnerableMethod) GetVulnerableParameters() []int32 {
	if o == nil || IsNil(o.VulnerableParameters) {
		var ret []int32
		return ret
	}
	return o.VulnerableParameters
}

// GetVulnerableParametersOk returns a tuple with the VulnerableParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VulnerableMethod) GetVulnerableParametersOk() ([]int32, bool) {
	if o == nil || IsNil(o.VulnerableParameters) {
		return nil, false
	}
	return o.VulnerableParameters, true
}

// HasVulnerableParameters returns a boolean if a field has been set.
func (o *VulnerableMethod) HasVulnerableParameters() bool {
	if o != nil && !IsNil(o.VulnerableParameters) {
		return true
	}

	return false
}

// SetVulnerableParameters gets a reference to the given []int32 and assigns it to the VulnerableParameters field.
func (o *VulnerableMethod) SetVulnerableParameters(v []int32) {
	o.VulnerableParameters = v
}

func (o VulnerableMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VulnerableMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.VulnerableParameters) {
		toSerialize["vulnerableParameters"] = o.VulnerableParameters
	}
	return toSerialize, nil
}

type NullableVulnerableMethod struct {
	value *VulnerableMethod
	isSet bool
}

func (v NullableVulnerableMethod) Get() *VulnerableMethod {
	return v.value
}

func (v *NullableVulnerableMethod) Set(val *VulnerableMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableVulnerableMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableVulnerableMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVulnerableMethod(val *VulnerableMethod) *NullableVulnerableMethod {
	return &NullableVulnerableMethod{value: val, isSet: true}
}

func (v NullableVulnerableMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVulnerableMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


