/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202608
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
	"time"
)

// checks if the SecurityEventDetailDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityEventDetailDocument{}

// SecurityEventDetailDocument struct for SecurityEventDetailDocument
type SecurityEventDetailDocument struct {
	AdvisoryReferenceIds []string `json:"advisoryReferenceIds,omitempty"`
	AffectedComponentVersionsCount *int32 `json:"affectedComponentVersionsCount,omitempty"`
	AffectedEcosystems []string `json:"affectedEcosystems,omitempty"`
	Cwes []string `json:"cwes,omitempty"`
	Detail *string `json:"detail,omitempty"`
	EventId *string `json:"eventId,omitempty"`
	EventSeverityCategory *string `json:"eventSeverityCategory,omitempty"`
	EventThreatType *string `json:"eventThreatType,omitempty"`
	Guidance *string `json:"guidance,omitempty"`
	IsKnownExploited *bool `json:"isKnownExploited,omitempty"`
	LastUpdatedDate *time.Time `json:"lastUpdatedDate,omitempty"`
	MalwareAttackVectors []string `json:"malwareAttackVectors,omitempty"`
	MalwareThreatTypes []string `json:"malwareThreatTypes,omitempty"`
	Overview *string `json:"overview,omitempty"`
	PublishedDate *time.Time `json:"publishedDate,omitempty"`
	SonatypeBlogUrl *string `json:"sonatypeBlogUrl,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewSecurityEventDetailDocument instantiates a new SecurityEventDetailDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityEventDetailDocument() *SecurityEventDetailDocument {
	this := SecurityEventDetailDocument{}
	return &this
}

// NewSecurityEventDetailDocumentWithDefaults instantiates a new SecurityEventDetailDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityEventDetailDocumentWithDefaults() *SecurityEventDetailDocument {
	this := SecurityEventDetailDocument{}
	return &this
}

// GetAdvisoryReferenceIds returns the AdvisoryReferenceIds field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetAdvisoryReferenceIds() []string {
	if o == nil || IsNil(o.AdvisoryReferenceIds) {
		var ret []string
		return ret
	}
	return o.AdvisoryReferenceIds
}

// GetAdvisoryReferenceIdsOk returns a tuple with the AdvisoryReferenceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetAdvisoryReferenceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AdvisoryReferenceIds) {
		return nil, false
	}
	return o.AdvisoryReferenceIds, true
}

// HasAdvisoryReferenceIds returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasAdvisoryReferenceIds() bool {
	if o != nil && !IsNil(o.AdvisoryReferenceIds) {
		return true
	}

	return false
}

// SetAdvisoryReferenceIds gets a reference to the given []string and assigns it to the AdvisoryReferenceIds field.
func (o *SecurityEventDetailDocument) SetAdvisoryReferenceIds(v []string) {
	o.AdvisoryReferenceIds = v
}

// GetAffectedComponentVersionsCount returns the AffectedComponentVersionsCount field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetAffectedComponentVersionsCount() int32 {
	if o == nil || IsNil(o.AffectedComponentVersionsCount) {
		var ret int32
		return ret
	}
	return *o.AffectedComponentVersionsCount
}

// GetAffectedComponentVersionsCountOk returns a tuple with the AffectedComponentVersionsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetAffectedComponentVersionsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AffectedComponentVersionsCount) {
		return nil, false
	}
	return o.AffectedComponentVersionsCount, true
}

// HasAffectedComponentVersionsCount returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasAffectedComponentVersionsCount() bool {
	if o != nil && !IsNil(o.AffectedComponentVersionsCount) {
		return true
	}

	return false
}

// SetAffectedComponentVersionsCount gets a reference to the given int32 and assigns it to the AffectedComponentVersionsCount field.
func (o *SecurityEventDetailDocument) SetAffectedComponentVersionsCount(v int32) {
	o.AffectedComponentVersionsCount = &v
}

// GetAffectedEcosystems returns the AffectedEcosystems field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetAffectedEcosystems() []string {
	if o == nil || IsNil(o.AffectedEcosystems) {
		var ret []string
		return ret
	}
	return o.AffectedEcosystems
}

// GetAffectedEcosystemsOk returns a tuple with the AffectedEcosystems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetAffectedEcosystemsOk() ([]string, bool) {
	if o == nil || IsNil(o.AffectedEcosystems) {
		return nil, false
	}
	return o.AffectedEcosystems, true
}

// HasAffectedEcosystems returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasAffectedEcosystems() bool {
	if o != nil && !IsNil(o.AffectedEcosystems) {
		return true
	}

	return false
}

// SetAffectedEcosystems gets a reference to the given []string and assigns it to the AffectedEcosystems field.
func (o *SecurityEventDetailDocument) SetAffectedEcosystems(v []string) {
	o.AffectedEcosystems = v
}

// GetCwes returns the Cwes field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetCwes() []string {
	if o == nil || IsNil(o.Cwes) {
		var ret []string
		return ret
	}
	return o.Cwes
}

// GetCwesOk returns a tuple with the Cwes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetCwesOk() ([]string, bool) {
	if o == nil || IsNil(o.Cwes) {
		return nil, false
	}
	return o.Cwes, true
}

// HasCwes returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasCwes() bool {
	if o != nil && !IsNil(o.Cwes) {
		return true
	}

	return false
}

// SetCwes gets a reference to the given []string and assigns it to the Cwes field.
func (o *SecurityEventDetailDocument) SetCwes(v []string) {
	o.Cwes = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *SecurityEventDetailDocument) SetDetail(v string) {
	o.Detail = &v
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetEventId() string {
	if o == nil || IsNil(o.EventId) {
		var ret string
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.EventId) {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasEventId() bool {
	if o != nil && !IsNil(o.EventId) {
		return true
	}

	return false
}

// SetEventId gets a reference to the given string and assigns it to the EventId field.
func (o *SecurityEventDetailDocument) SetEventId(v string) {
	o.EventId = &v
}

// GetEventSeverityCategory returns the EventSeverityCategory field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetEventSeverityCategory() string {
	if o == nil || IsNil(o.EventSeverityCategory) {
		var ret string
		return ret
	}
	return *o.EventSeverityCategory
}

// GetEventSeverityCategoryOk returns a tuple with the EventSeverityCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetEventSeverityCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.EventSeverityCategory) {
		return nil, false
	}
	return o.EventSeverityCategory, true
}

// HasEventSeverityCategory returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasEventSeverityCategory() bool {
	if o != nil && !IsNil(o.EventSeverityCategory) {
		return true
	}

	return false
}

// SetEventSeverityCategory gets a reference to the given string and assigns it to the EventSeverityCategory field.
func (o *SecurityEventDetailDocument) SetEventSeverityCategory(v string) {
	o.EventSeverityCategory = &v
}

// GetEventThreatType returns the EventThreatType field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetEventThreatType() string {
	if o == nil || IsNil(o.EventThreatType) {
		var ret string
		return ret
	}
	return *o.EventThreatType
}

// GetEventThreatTypeOk returns a tuple with the EventThreatType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetEventThreatTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventThreatType) {
		return nil, false
	}
	return o.EventThreatType, true
}

// HasEventThreatType returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasEventThreatType() bool {
	if o != nil && !IsNil(o.EventThreatType) {
		return true
	}

	return false
}

// SetEventThreatType gets a reference to the given string and assigns it to the EventThreatType field.
func (o *SecurityEventDetailDocument) SetEventThreatType(v string) {
	o.EventThreatType = &v
}

// GetGuidance returns the Guidance field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetGuidance() string {
	if o == nil || IsNil(o.Guidance) {
		var ret string
		return ret
	}
	return *o.Guidance
}

// GetGuidanceOk returns a tuple with the Guidance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetGuidanceOk() (*string, bool) {
	if o == nil || IsNil(o.Guidance) {
		return nil, false
	}
	return o.Guidance, true
}

// HasGuidance returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasGuidance() bool {
	if o != nil && !IsNil(o.Guidance) {
		return true
	}

	return false
}

// SetGuidance gets a reference to the given string and assigns it to the Guidance field.
func (o *SecurityEventDetailDocument) SetGuidance(v string) {
	o.Guidance = &v
}

// GetIsKnownExploited returns the IsKnownExploited field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetIsKnownExploited() bool {
	if o == nil || IsNil(o.IsKnownExploited) {
		var ret bool
		return ret
	}
	return *o.IsKnownExploited
}

// GetIsKnownExploitedOk returns a tuple with the IsKnownExploited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetIsKnownExploitedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsKnownExploited) {
		return nil, false
	}
	return o.IsKnownExploited, true
}

// HasIsKnownExploited returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasIsKnownExploited() bool {
	if o != nil && !IsNil(o.IsKnownExploited) {
		return true
	}

	return false
}

// SetIsKnownExploited gets a reference to the given bool and assigns it to the IsKnownExploited field.
func (o *SecurityEventDetailDocument) SetIsKnownExploited(v bool) {
	o.IsKnownExploited = &v
}

// GetLastUpdatedDate returns the LastUpdatedDate field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetLastUpdatedDate() time.Time {
	if o == nil || IsNil(o.LastUpdatedDate) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedDate
}

// GetLastUpdatedDateOk returns a tuple with the LastUpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetLastUpdatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdatedDate) {
		return nil, false
	}
	return o.LastUpdatedDate, true
}

// HasLastUpdatedDate returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasLastUpdatedDate() bool {
	if o != nil && !IsNil(o.LastUpdatedDate) {
		return true
	}

	return false
}

// SetLastUpdatedDate gets a reference to the given time.Time and assigns it to the LastUpdatedDate field.
func (o *SecurityEventDetailDocument) SetLastUpdatedDate(v time.Time) {
	o.LastUpdatedDate = &v
}

// GetMalwareAttackVectors returns the MalwareAttackVectors field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetMalwareAttackVectors() []string {
	if o == nil || IsNil(o.MalwareAttackVectors) {
		var ret []string
		return ret
	}
	return o.MalwareAttackVectors
}

// GetMalwareAttackVectorsOk returns a tuple with the MalwareAttackVectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetMalwareAttackVectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.MalwareAttackVectors) {
		return nil, false
	}
	return o.MalwareAttackVectors, true
}

// HasMalwareAttackVectors returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasMalwareAttackVectors() bool {
	if o != nil && !IsNil(o.MalwareAttackVectors) {
		return true
	}

	return false
}

// SetMalwareAttackVectors gets a reference to the given []string and assigns it to the MalwareAttackVectors field.
func (o *SecurityEventDetailDocument) SetMalwareAttackVectors(v []string) {
	o.MalwareAttackVectors = v
}

// GetMalwareThreatTypes returns the MalwareThreatTypes field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetMalwareThreatTypes() []string {
	if o == nil || IsNil(o.MalwareThreatTypes) {
		var ret []string
		return ret
	}
	return o.MalwareThreatTypes
}

// GetMalwareThreatTypesOk returns a tuple with the MalwareThreatTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetMalwareThreatTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.MalwareThreatTypes) {
		return nil, false
	}
	return o.MalwareThreatTypes, true
}

// HasMalwareThreatTypes returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasMalwareThreatTypes() bool {
	if o != nil && !IsNil(o.MalwareThreatTypes) {
		return true
	}

	return false
}

// SetMalwareThreatTypes gets a reference to the given []string and assigns it to the MalwareThreatTypes field.
func (o *SecurityEventDetailDocument) SetMalwareThreatTypes(v []string) {
	o.MalwareThreatTypes = v
}

// GetOverview returns the Overview field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetOverview() string {
	if o == nil || IsNil(o.Overview) {
		var ret string
		return ret
	}
	return *o.Overview
}

// GetOverviewOk returns a tuple with the Overview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetOverviewOk() (*string, bool) {
	if o == nil || IsNil(o.Overview) {
		return nil, false
	}
	return o.Overview, true
}

// HasOverview returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasOverview() bool {
	if o != nil && !IsNil(o.Overview) {
		return true
	}

	return false
}

// SetOverview gets a reference to the given string and assigns it to the Overview field.
func (o *SecurityEventDetailDocument) SetOverview(v string) {
	o.Overview = &v
}

// GetPublishedDate returns the PublishedDate field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetPublishedDate() time.Time {
	if o == nil || IsNil(o.PublishedDate) {
		var ret time.Time
		return ret
	}
	return *o.PublishedDate
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetPublishedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedDate) {
		return nil, false
	}
	return o.PublishedDate, true
}

// HasPublishedDate returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasPublishedDate() bool {
	if o != nil && !IsNil(o.PublishedDate) {
		return true
	}

	return false
}

// SetPublishedDate gets a reference to the given time.Time and assigns it to the PublishedDate field.
func (o *SecurityEventDetailDocument) SetPublishedDate(v time.Time) {
	o.PublishedDate = &v
}

// GetSonatypeBlogUrl returns the SonatypeBlogUrl field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetSonatypeBlogUrl() string {
	if o == nil || IsNil(o.SonatypeBlogUrl) {
		var ret string
		return ret
	}
	return *o.SonatypeBlogUrl
}

// GetSonatypeBlogUrlOk returns a tuple with the SonatypeBlogUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetSonatypeBlogUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SonatypeBlogUrl) {
		return nil, false
	}
	return o.SonatypeBlogUrl, true
}

// HasSonatypeBlogUrl returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasSonatypeBlogUrl() bool {
	if o != nil && !IsNil(o.SonatypeBlogUrl) {
		return true
	}

	return false
}

// SetSonatypeBlogUrl gets a reference to the given string and assigns it to the SonatypeBlogUrl field.
func (o *SecurityEventDetailDocument) SetSonatypeBlogUrl(v string) {
	o.SonatypeBlogUrl = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *SecurityEventDetailDocument) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityEventDetailDocument) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *SecurityEventDetailDocument) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *SecurityEventDetailDocument) SetTitle(v string) {
	o.Title = &v
}

func (o SecurityEventDetailDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityEventDetailDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdvisoryReferenceIds) {
		toSerialize["advisoryReferenceIds"] = o.AdvisoryReferenceIds
	}
	if !IsNil(o.AffectedComponentVersionsCount) {
		toSerialize["affectedComponentVersionsCount"] = o.AffectedComponentVersionsCount
	}
	if !IsNil(o.AffectedEcosystems) {
		toSerialize["affectedEcosystems"] = o.AffectedEcosystems
	}
	if !IsNil(o.Cwes) {
		toSerialize["cwes"] = o.Cwes
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.EventId) {
		toSerialize["eventId"] = o.EventId
	}
	if !IsNil(o.EventSeverityCategory) {
		toSerialize["eventSeverityCategory"] = o.EventSeverityCategory
	}
	if !IsNil(o.EventThreatType) {
		toSerialize["eventThreatType"] = o.EventThreatType
	}
	if !IsNil(o.Guidance) {
		toSerialize["guidance"] = o.Guidance
	}
	if !IsNil(o.IsKnownExploited) {
		toSerialize["isKnownExploited"] = o.IsKnownExploited
	}
	if !IsNil(o.LastUpdatedDate) {
		toSerialize["lastUpdatedDate"] = o.LastUpdatedDate
	}
	if !IsNil(o.MalwareAttackVectors) {
		toSerialize["malwareAttackVectors"] = o.MalwareAttackVectors
	}
	if !IsNil(o.MalwareThreatTypes) {
		toSerialize["malwareThreatTypes"] = o.MalwareThreatTypes
	}
	if !IsNil(o.Overview) {
		toSerialize["overview"] = o.Overview
	}
	if !IsNil(o.PublishedDate) {
		toSerialize["publishedDate"] = o.PublishedDate
	}
	if !IsNil(o.SonatypeBlogUrl) {
		toSerialize["sonatypeBlogUrl"] = o.SonatypeBlogUrl
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableSecurityEventDetailDocument struct {
	value *SecurityEventDetailDocument
	isSet bool
}

func (v NullableSecurityEventDetailDocument) Get() *SecurityEventDetailDocument {
	return v.value
}

func (v *NullableSecurityEventDetailDocument) Set(val *SecurityEventDetailDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityEventDetailDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityEventDetailDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityEventDetailDocument(val *SecurityEventDetailDocument) *NullableSecurityEventDetailDocument {
	return &NullableSecurityEventDetailDocument{value: val, isSet: true}
}

func (v NullableSecurityEventDetailDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityEventDetailDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


