/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202605
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteUsersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteUsersRequest{}

// InviteUsersRequest struct for InviteUsersRequest
type InviteUsersRequest struct {
	Emails []string `json:"emails"`
}

type _InviteUsersRequest InviteUsersRequest

// NewInviteUsersRequest instantiates a new InviteUsersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteUsersRequest(emails []string) *InviteUsersRequest {
	this := InviteUsersRequest{}
	this.Emails = emails
	return &this
}

// NewInviteUsersRequestWithDefaults instantiates a new InviteUsersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteUsersRequestWithDefaults() *InviteUsersRequest {
	this := InviteUsersRequest{}
	return &this
}

// GetEmails returns the Emails field value
func (o *InviteUsersRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *InviteUsersRequest) GetEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *InviteUsersRequest) SetEmails(v []string) {
	o.Emails = v
}

func (o InviteUsersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteUsersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *InviteUsersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteUsersRequest := _InviteUsersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteUsersRequest)

	if err != nil {
		return err
	}

	*o = InviteUsersRequest(varInviteUsersRequest)

	return err
}

type NullableInviteUsersRequest struct {
	value *InviteUsersRequest
	isSet bool
}

func (v NullableInviteUsersRequest) Get() *InviteUsersRequest {
	return v.value
}

func (v *NullableInviteUsersRequest) Set(val *InviteUsersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteUsersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteUsersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteUsersRequest(val *InviteUsersRequest) *NullableInviteUsersRequest {
	return &NullableInviteUsersRequest{value: val, isSet: true}
}

func (v NullableInviteUsersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteUsersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


