/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the LatestVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LatestVersionRequest{}

// LatestVersionRequest Request body containing the component PURL
type LatestVersionRequest struct {
	Purl *string `json:"purl,omitempty"`
}

// NewLatestVersionRequest instantiates a new LatestVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLatestVersionRequest() *LatestVersionRequest {
	this := LatestVersionRequest{}
	return &this
}

// NewLatestVersionRequestWithDefaults instantiates a new LatestVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLatestVersionRequestWithDefaults() *LatestVersionRequest {
	this := LatestVersionRequest{}
	return &this
}

// GetPurl returns the Purl field value if set, zero value otherwise.
func (o *LatestVersionRequest) GetPurl() string {
	if o == nil || IsNil(o.Purl) {
		var ret string
		return ret
	}
	return *o.Purl
}

// GetPurlOk returns a tuple with the Purl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LatestVersionRequest) GetPurlOk() (*string, bool) {
	if o == nil || IsNil(o.Purl) {
		return nil, false
	}
	return o.Purl, true
}

// HasPurl returns a boolean if a field has been set.
func (o *LatestVersionRequest) HasPurl() bool {
	if o != nil && !IsNil(o.Purl) {
		return true
	}

	return false
}

// SetPurl gets a reference to the given string and assigns it to the Purl field.
func (o *LatestVersionRequest) SetPurl(v string) {
	o.Purl = &v
}

func (o LatestVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LatestVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Purl) {
		toSerialize["purl"] = o.Purl
	}
	return toSerialize, nil
}

type NullableLatestVersionRequest struct {
	value *LatestVersionRequest
	isSet bool
}

func (v NullableLatestVersionRequest) Get() *LatestVersionRequest {
	return v.value
}

func (v *NullableLatestVersionRequest) Set(val *LatestVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLatestVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLatestVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLatestVersionRequest(val *LatestVersionRequest) *NullableLatestVersionRequest {
	return &NullableLatestVersionRequest{value: val, isSet: true}
}

func (v NullableLatestVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLatestVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


