/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the RecommendedVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecommendedVersion{}

// RecommendedVersion struct for RecommendedVersion
type RecommendedVersion struct {
	BreakingChangesCount *string `json:"breakingChangesCount,omitempty"`
	DeveloperTrustScore *int32 `json:"developerTrustScore,omitempty"`
	DirectVulnerabilities map[string]float64 `json:"directVulnerabilities,omitempty"`
	DtsDimensions *DtsDimensions `json:"dtsDimensions,omitempty"`
	LicenseThreatLevels map[string]int32 `json:"licenseThreatLevels,omitempty"`
	MaxSeverity *float64 `json:"maxSeverity,omitempty"`
	PolicyCompliance *PolicyCompliance `json:"policyCompliance,omitempty"`
	TransitiveVulnerabilities map[string]float64 `json:"transitiveVulnerabilities,omitempty"`
	Version *string `json:"version,omitempty"`
	VulnerableMethods []RecommendationVulnerableMethod `json:"vulnerableMethods,omitempty"`
}

// NewRecommendedVersion instantiates a new RecommendedVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendedVersion() *RecommendedVersion {
	this := RecommendedVersion{}
	return &this
}

// NewRecommendedVersionWithDefaults instantiates a new RecommendedVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendedVersionWithDefaults() *RecommendedVersion {
	this := RecommendedVersion{}
	return &this
}

// GetBreakingChangesCount returns the BreakingChangesCount field value if set, zero value otherwise.
func (o *RecommendedVersion) GetBreakingChangesCount() string {
	if o == nil || IsNil(o.BreakingChangesCount) {
		var ret string
		return ret
	}
	return *o.BreakingChangesCount
}

// GetBreakingChangesCountOk returns a tuple with the BreakingChangesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetBreakingChangesCountOk() (*string, bool) {
	if o == nil || IsNil(o.BreakingChangesCount) {
		return nil, false
	}
	return o.BreakingChangesCount, true
}

// HasBreakingChangesCount returns a boolean if a field has been set.
func (o *RecommendedVersion) HasBreakingChangesCount() bool {
	if o != nil && !IsNil(o.BreakingChangesCount) {
		return true
	}

	return false
}

// SetBreakingChangesCount gets a reference to the given string and assigns it to the BreakingChangesCount field.
func (o *RecommendedVersion) SetBreakingChangesCount(v string) {
	o.BreakingChangesCount = &v
}

// GetDeveloperTrustScore returns the DeveloperTrustScore field value if set, zero value otherwise.
func (o *RecommendedVersion) GetDeveloperTrustScore() int32 {
	if o == nil || IsNil(o.DeveloperTrustScore) {
		var ret int32
		return ret
	}
	return *o.DeveloperTrustScore
}

// GetDeveloperTrustScoreOk returns a tuple with the DeveloperTrustScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetDeveloperTrustScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.DeveloperTrustScore) {
		return nil, false
	}
	return o.DeveloperTrustScore, true
}

// HasDeveloperTrustScore returns a boolean if a field has been set.
func (o *RecommendedVersion) HasDeveloperTrustScore() bool {
	if o != nil && !IsNil(o.DeveloperTrustScore) {
		return true
	}

	return false
}

// SetDeveloperTrustScore gets a reference to the given int32 and assigns it to the DeveloperTrustScore field.
func (o *RecommendedVersion) SetDeveloperTrustScore(v int32) {
	o.DeveloperTrustScore = &v
}

// GetDirectVulnerabilities returns the DirectVulnerabilities field value if set, zero value otherwise.
func (o *RecommendedVersion) GetDirectVulnerabilities() map[string]float64 {
	if o == nil || IsNil(o.DirectVulnerabilities) {
		var ret map[string]float64
		return ret
	}
	return o.DirectVulnerabilities
}

// GetDirectVulnerabilitiesOk returns a tuple with the DirectVulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetDirectVulnerabilitiesOk() (map[string]float64, bool) {
	if o == nil || IsNil(o.DirectVulnerabilities) {
		return map[string]float64{}, false
	}
	return o.DirectVulnerabilities, true
}

// HasDirectVulnerabilities returns a boolean if a field has been set.
func (o *RecommendedVersion) HasDirectVulnerabilities() bool {
	if o != nil && !IsNil(o.DirectVulnerabilities) {
		return true
	}

	return false
}

// SetDirectVulnerabilities gets a reference to the given map[string]float64 and assigns it to the DirectVulnerabilities field.
func (o *RecommendedVersion) SetDirectVulnerabilities(v map[string]float64) {
	o.DirectVulnerabilities = v
}

// GetDtsDimensions returns the DtsDimensions field value if set, zero value otherwise.
func (o *RecommendedVersion) GetDtsDimensions() DtsDimensions {
	if o == nil || IsNil(o.DtsDimensions) {
		var ret DtsDimensions
		return ret
	}
	return *o.DtsDimensions
}

// GetDtsDimensionsOk returns a tuple with the DtsDimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetDtsDimensionsOk() (*DtsDimensions, bool) {
	if o == nil || IsNil(o.DtsDimensions) {
		return nil, false
	}
	return o.DtsDimensions, true
}

// HasDtsDimensions returns a boolean if a field has been set.
func (o *RecommendedVersion) HasDtsDimensions() bool {
	if o != nil && !IsNil(o.DtsDimensions) {
		return true
	}

	return false
}

// SetDtsDimensions gets a reference to the given DtsDimensions and assigns it to the DtsDimensions field.
func (o *RecommendedVersion) SetDtsDimensions(v DtsDimensions) {
	o.DtsDimensions = &v
}

// GetLicenseThreatLevels returns the LicenseThreatLevels field value if set, zero value otherwise.
func (o *RecommendedVersion) GetLicenseThreatLevels() map[string]int32 {
	if o == nil || IsNil(o.LicenseThreatLevels) {
		var ret map[string]int32
		return ret
	}
	return o.LicenseThreatLevels
}

// GetLicenseThreatLevelsOk returns a tuple with the LicenseThreatLevels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetLicenseThreatLevelsOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.LicenseThreatLevels) {
		return map[string]int32{}, false
	}
	return o.LicenseThreatLevels, true
}

// HasLicenseThreatLevels returns a boolean if a field has been set.
func (o *RecommendedVersion) HasLicenseThreatLevels() bool {
	if o != nil && !IsNil(o.LicenseThreatLevels) {
		return true
	}

	return false
}

// SetLicenseThreatLevels gets a reference to the given map[string]int32 and assigns it to the LicenseThreatLevels field.
func (o *RecommendedVersion) SetLicenseThreatLevels(v map[string]int32) {
	o.LicenseThreatLevels = v
}

// GetMaxSeverity returns the MaxSeverity field value if set, zero value otherwise.
func (o *RecommendedVersion) GetMaxSeverity() float64 {
	if o == nil || IsNil(o.MaxSeverity) {
		var ret float64
		return ret
	}
	return *o.MaxSeverity
}

// GetMaxSeverityOk returns a tuple with the MaxSeverity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetMaxSeverityOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxSeverity) {
		return nil, false
	}
	return o.MaxSeverity, true
}

// HasMaxSeverity returns a boolean if a field has been set.
func (o *RecommendedVersion) HasMaxSeverity() bool {
	if o != nil && !IsNil(o.MaxSeverity) {
		return true
	}

	return false
}

// SetMaxSeverity gets a reference to the given float64 and assigns it to the MaxSeverity field.
func (o *RecommendedVersion) SetMaxSeverity(v float64) {
	o.MaxSeverity = &v
}

// GetPolicyCompliance returns the PolicyCompliance field value if set, zero value otherwise.
func (o *RecommendedVersion) GetPolicyCompliance() PolicyCompliance {
	if o == nil || IsNil(o.PolicyCompliance) {
		var ret PolicyCompliance
		return ret
	}
	return *o.PolicyCompliance
}

// GetPolicyComplianceOk returns a tuple with the PolicyCompliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetPolicyComplianceOk() (*PolicyCompliance, bool) {
	if o == nil || IsNil(o.PolicyCompliance) {
		return nil, false
	}
	return o.PolicyCompliance, true
}

// HasPolicyCompliance returns a boolean if a field has been set.
func (o *RecommendedVersion) HasPolicyCompliance() bool {
	if o != nil && !IsNil(o.PolicyCompliance) {
		return true
	}

	return false
}

// SetPolicyCompliance gets a reference to the given PolicyCompliance and assigns it to the PolicyCompliance field.
func (o *RecommendedVersion) SetPolicyCompliance(v PolicyCompliance) {
	o.PolicyCompliance = &v
}

// GetTransitiveVulnerabilities returns the TransitiveVulnerabilities field value if set, zero value otherwise.
func (o *RecommendedVersion) GetTransitiveVulnerabilities() map[string]float64 {
	if o == nil || IsNil(o.TransitiveVulnerabilities) {
		var ret map[string]float64
		return ret
	}
	return o.TransitiveVulnerabilities
}

// GetTransitiveVulnerabilitiesOk returns a tuple with the TransitiveVulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetTransitiveVulnerabilitiesOk() (map[string]float64, bool) {
	if o == nil || IsNil(o.TransitiveVulnerabilities) {
		return map[string]float64{}, false
	}
	return o.TransitiveVulnerabilities, true
}

// HasTransitiveVulnerabilities returns a boolean if a field has been set.
func (o *RecommendedVersion) HasTransitiveVulnerabilities() bool {
	if o != nil && !IsNil(o.TransitiveVulnerabilities) {
		return true
	}

	return false
}

// SetTransitiveVulnerabilities gets a reference to the given map[string]float64 and assigns it to the TransitiveVulnerabilities field.
func (o *RecommendedVersion) SetTransitiveVulnerabilities(v map[string]float64) {
	o.TransitiveVulnerabilities = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *RecommendedVersion) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *RecommendedVersion) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *RecommendedVersion) SetVersion(v string) {
	o.Version = &v
}

// GetVulnerableMethods returns the VulnerableMethods field value if set, zero value otherwise.
func (o *RecommendedVersion) GetVulnerableMethods() []RecommendationVulnerableMethod {
	if o == nil || IsNil(o.VulnerableMethods) {
		var ret []RecommendationVulnerableMethod
		return ret
	}
	return o.VulnerableMethods
}

// GetVulnerableMethodsOk returns a tuple with the VulnerableMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendedVersion) GetVulnerableMethodsOk() ([]RecommendationVulnerableMethod, bool) {
	if o == nil || IsNil(o.VulnerableMethods) {
		return nil, false
	}
	return o.VulnerableMethods, true
}

// HasVulnerableMethods returns a boolean if a field has been set.
func (o *RecommendedVersion) HasVulnerableMethods() bool {
	if o != nil && !IsNil(o.VulnerableMethods) {
		return true
	}

	return false
}

// SetVulnerableMethods gets a reference to the given []RecommendationVulnerableMethod and assigns it to the VulnerableMethods field.
func (o *RecommendedVersion) SetVulnerableMethods(v []RecommendationVulnerableMethod) {
	o.VulnerableMethods = v
}

func (o RecommendedVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecommendedVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BreakingChangesCount) {
		toSerialize["breakingChangesCount"] = o.BreakingChangesCount
	}
	if !IsNil(o.DeveloperTrustScore) {
		toSerialize["developerTrustScore"] = o.DeveloperTrustScore
	}
	if !IsNil(o.DirectVulnerabilities) {
		toSerialize["directVulnerabilities"] = o.DirectVulnerabilities
	}
	if !IsNil(o.DtsDimensions) {
		toSerialize["dtsDimensions"] = o.DtsDimensions
	}
	if !IsNil(o.LicenseThreatLevels) {
		toSerialize["licenseThreatLevels"] = o.LicenseThreatLevels
	}
	if !IsNil(o.MaxSeverity) {
		toSerialize["maxSeverity"] = o.MaxSeverity
	}
	if !IsNil(o.PolicyCompliance) {
		toSerialize["policyCompliance"] = o.PolicyCompliance
	}
	if !IsNil(o.TransitiveVulnerabilities) {
		toSerialize["transitiveVulnerabilities"] = o.TransitiveVulnerabilities
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.VulnerableMethods) {
		toSerialize["vulnerableMethods"] = o.VulnerableMethods
	}
	return toSerialize, nil
}

type NullableRecommendedVersion struct {
	value *RecommendedVersion
	isSet bool
}

func (v NullableRecommendedVersion) Get() *RecommendedVersion {
	return v.value
}

func (v *NullableRecommendedVersion) Set(val *RecommendedVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendedVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendedVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendedVersion(val *RecommendedVersion) *NullableRecommendedVersion {
	return &NullableRecommendedVersion{value: val, isSet: true}
}

func (v NullableRecommendedVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendedVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


