/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the OssiUsageSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OssiUsageSummary{}

// OssiUsageSummary struct for OssiUsageSummary
type OssiUsageSummary struct {
	DataRange *OssiUsageDataRange `json:"dataRange,omitempty"`
	MaxCredits *float32 `json:"maxCredits,omitempty"`
	MonthlyAverage *float32 `json:"monthlyAverage,omitempty"`
	TotalCredits *float32 `json:"totalCredits,omitempty"`
}

// NewOssiUsageSummary instantiates a new OssiUsageSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOssiUsageSummary() *OssiUsageSummary {
	this := OssiUsageSummary{}
	return &this
}

// NewOssiUsageSummaryWithDefaults instantiates a new OssiUsageSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOssiUsageSummaryWithDefaults() *OssiUsageSummary {
	this := OssiUsageSummary{}
	return &this
}

// GetDataRange returns the DataRange field value if set, zero value otherwise.
func (o *OssiUsageSummary) GetDataRange() OssiUsageDataRange {
	if o == nil || IsNil(o.DataRange) {
		var ret OssiUsageDataRange
		return ret
	}
	return *o.DataRange
}

// GetDataRangeOk returns a tuple with the DataRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OssiUsageSummary) GetDataRangeOk() (*OssiUsageDataRange, bool) {
	if o == nil || IsNil(o.DataRange) {
		return nil, false
	}
	return o.DataRange, true
}

// HasDataRange returns a boolean if a field has been set.
func (o *OssiUsageSummary) HasDataRange() bool {
	if o != nil && !IsNil(o.DataRange) {
		return true
	}

	return false
}

// SetDataRange gets a reference to the given OssiUsageDataRange and assigns it to the DataRange field.
func (o *OssiUsageSummary) SetDataRange(v OssiUsageDataRange) {
	o.DataRange = &v
}

// GetMaxCredits returns the MaxCredits field value if set, zero value otherwise.
func (o *OssiUsageSummary) GetMaxCredits() float32 {
	if o == nil || IsNil(o.MaxCredits) {
		var ret float32
		return ret
	}
	return *o.MaxCredits
}

// GetMaxCreditsOk returns a tuple with the MaxCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OssiUsageSummary) GetMaxCreditsOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxCredits) {
		return nil, false
	}
	return o.MaxCredits, true
}

// HasMaxCredits returns a boolean if a field has been set.
func (o *OssiUsageSummary) HasMaxCredits() bool {
	if o != nil && !IsNil(o.MaxCredits) {
		return true
	}

	return false
}

// SetMaxCredits gets a reference to the given float32 and assigns it to the MaxCredits field.
func (o *OssiUsageSummary) SetMaxCredits(v float32) {
	o.MaxCredits = &v
}

// GetMonthlyAverage returns the MonthlyAverage field value if set, zero value otherwise.
func (o *OssiUsageSummary) GetMonthlyAverage() float32 {
	if o == nil || IsNil(o.MonthlyAverage) {
		var ret float32
		return ret
	}
	return *o.MonthlyAverage
}

// GetMonthlyAverageOk returns a tuple with the MonthlyAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OssiUsageSummary) GetMonthlyAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.MonthlyAverage) {
		return nil, false
	}
	return o.MonthlyAverage, true
}

// HasMonthlyAverage returns a boolean if a field has been set.
func (o *OssiUsageSummary) HasMonthlyAverage() bool {
	if o != nil && !IsNil(o.MonthlyAverage) {
		return true
	}

	return false
}

// SetMonthlyAverage gets a reference to the given float32 and assigns it to the MonthlyAverage field.
func (o *OssiUsageSummary) SetMonthlyAverage(v float32) {
	o.MonthlyAverage = &v
}

// GetTotalCredits returns the TotalCredits field value if set, zero value otherwise.
func (o *OssiUsageSummary) GetTotalCredits() float32 {
	if o == nil || IsNil(o.TotalCredits) {
		var ret float32
		return ret
	}
	return *o.TotalCredits
}

// GetTotalCreditsOk returns a tuple with the TotalCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OssiUsageSummary) GetTotalCreditsOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCredits) {
		return nil, false
	}
	return o.TotalCredits, true
}

// HasTotalCredits returns a boolean if a field has been set.
func (o *OssiUsageSummary) HasTotalCredits() bool {
	if o != nil && !IsNil(o.TotalCredits) {
		return true
	}

	return false
}

// SetTotalCredits gets a reference to the given float32 and assigns it to the TotalCredits field.
func (o *OssiUsageSummary) SetTotalCredits(v float32) {
	o.TotalCredits = &v
}

func (o OssiUsageSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OssiUsageSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataRange) {
		toSerialize["dataRange"] = o.DataRange
	}
	if !IsNil(o.MaxCredits) {
		toSerialize["maxCredits"] = o.MaxCredits
	}
	if !IsNil(o.MonthlyAverage) {
		toSerialize["monthlyAverage"] = o.MonthlyAverage
	}
	if !IsNil(o.TotalCredits) {
		toSerialize["totalCredits"] = o.TotalCredits
	}
	return toSerialize, nil
}

type NullableOssiUsageSummary struct {
	value *OssiUsageSummary
	isSet bool
}

func (v NullableOssiUsageSummary) Get() *OssiUsageSummary {
	return v.value
}

func (v *NullableOssiUsageSummary) Set(val *OssiUsageSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableOssiUsageSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableOssiUsageSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOssiUsageSummary(val *OssiUsageSummary) *NullableOssiUsageSummary {
	return &NullableOssiUsageSummary{value: val, isSet: true}
}

func (v NullableOssiUsageSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOssiUsageSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


