/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202608
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the CumulativeCreditUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CumulativeCreditUsage{}

// CumulativeCreditUsage struct for CumulativeCreditUsage
type CumulativeCreditUsage struct {
	CreditLimit *float32 `json:"creditLimit,omitempty"`
	DailyAverage *float32 `json:"dailyAverage,omitempty"`
	DailyUsage []DailyCreditUsage `json:"dailyUsage,omitempty"`
	PeakDay *float32 `json:"peakDay,omitempty"`
	TotalCreditsUsed *float32 `json:"totalCreditsUsed,omitempty"`
}

// NewCumulativeCreditUsage instantiates a new CumulativeCreditUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCumulativeCreditUsage() *CumulativeCreditUsage {
	this := CumulativeCreditUsage{}
	return &this
}

// NewCumulativeCreditUsageWithDefaults instantiates a new CumulativeCreditUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCumulativeCreditUsageWithDefaults() *CumulativeCreditUsage {
	this := CumulativeCreditUsage{}
	return &this
}

// GetCreditLimit returns the CreditLimit field value if set, zero value otherwise.
func (o *CumulativeCreditUsage) GetCreditLimit() float32 {
	if o == nil || IsNil(o.CreditLimit) {
		var ret float32
		return ret
	}
	return *o.CreditLimit
}

// GetCreditLimitOk returns a tuple with the CreditLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CumulativeCreditUsage) GetCreditLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.CreditLimit) {
		return nil, false
	}
	return o.CreditLimit, true
}

// HasCreditLimit returns a boolean if a field has been set.
func (o *CumulativeCreditUsage) HasCreditLimit() bool {
	if o != nil && !IsNil(o.CreditLimit) {
		return true
	}

	return false
}

// SetCreditLimit gets a reference to the given float32 and assigns it to the CreditLimit field.
func (o *CumulativeCreditUsage) SetCreditLimit(v float32) {
	o.CreditLimit = &v
}

// GetDailyAverage returns the DailyAverage field value if set, zero value otherwise.
func (o *CumulativeCreditUsage) GetDailyAverage() float32 {
	if o == nil || IsNil(o.DailyAverage) {
		var ret float32
		return ret
	}
	return *o.DailyAverage
}

// GetDailyAverageOk returns a tuple with the DailyAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CumulativeCreditUsage) GetDailyAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.DailyAverage) {
		return nil, false
	}
	return o.DailyAverage, true
}

// HasDailyAverage returns a boolean if a field has been set.
func (o *CumulativeCreditUsage) HasDailyAverage() bool {
	if o != nil && !IsNil(o.DailyAverage) {
		return true
	}

	return false
}

// SetDailyAverage gets a reference to the given float32 and assigns it to the DailyAverage field.
func (o *CumulativeCreditUsage) SetDailyAverage(v float32) {
	o.DailyAverage = &v
}

// GetDailyUsage returns the DailyUsage field value if set, zero value otherwise.
func (o *CumulativeCreditUsage) GetDailyUsage() []DailyCreditUsage {
	if o == nil || IsNil(o.DailyUsage) {
		var ret []DailyCreditUsage
		return ret
	}
	return o.DailyUsage
}

// GetDailyUsageOk returns a tuple with the DailyUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CumulativeCreditUsage) GetDailyUsageOk() ([]DailyCreditUsage, bool) {
	if o == nil || IsNil(o.DailyUsage) {
		return nil, false
	}
	return o.DailyUsage, true
}

// HasDailyUsage returns a boolean if a field has been set.
func (o *CumulativeCreditUsage) HasDailyUsage() bool {
	if o != nil && !IsNil(o.DailyUsage) {
		return true
	}

	return false
}

// SetDailyUsage gets a reference to the given []DailyCreditUsage and assigns it to the DailyUsage field.
func (o *CumulativeCreditUsage) SetDailyUsage(v []DailyCreditUsage) {
	o.DailyUsage = v
}

// GetPeakDay returns the PeakDay field value if set, zero value otherwise.
func (o *CumulativeCreditUsage) GetPeakDay() float32 {
	if o == nil || IsNil(o.PeakDay) {
		var ret float32
		return ret
	}
	return *o.PeakDay
}

// GetPeakDayOk returns a tuple with the PeakDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CumulativeCreditUsage) GetPeakDayOk() (*float32, bool) {
	if o == nil || IsNil(o.PeakDay) {
		return nil, false
	}
	return o.PeakDay, true
}

// HasPeakDay returns a boolean if a field has been set.
func (o *CumulativeCreditUsage) HasPeakDay() bool {
	if o != nil && !IsNil(o.PeakDay) {
		return true
	}

	return false
}

// SetPeakDay gets a reference to the given float32 and assigns it to the PeakDay field.
func (o *CumulativeCreditUsage) SetPeakDay(v float32) {
	o.PeakDay = &v
}

// GetTotalCreditsUsed returns the TotalCreditsUsed field value if set, zero value otherwise.
func (o *CumulativeCreditUsage) GetTotalCreditsUsed() float32 {
	if o == nil || IsNil(o.TotalCreditsUsed) {
		var ret float32
		return ret
	}
	return *o.TotalCreditsUsed
}

// GetTotalCreditsUsedOk returns a tuple with the TotalCreditsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CumulativeCreditUsage) GetTotalCreditsUsedOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCreditsUsed) {
		return nil, false
	}
	return o.TotalCreditsUsed, true
}

// HasTotalCreditsUsed returns a boolean if a field has been set.
func (o *CumulativeCreditUsage) HasTotalCreditsUsed() bool {
	if o != nil && !IsNil(o.TotalCreditsUsed) {
		return true
	}

	return false
}

// SetTotalCreditsUsed gets a reference to the given float32 and assigns it to the TotalCreditsUsed field.
func (o *CumulativeCreditUsage) SetTotalCreditsUsed(v float32) {
	o.TotalCreditsUsed = &v
}

func (o CumulativeCreditUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CumulativeCreditUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreditLimit) {
		toSerialize["creditLimit"] = o.CreditLimit
	}
	if !IsNil(o.DailyAverage) {
		toSerialize["dailyAverage"] = o.DailyAverage
	}
	if !IsNil(o.DailyUsage) {
		toSerialize["dailyUsage"] = o.DailyUsage
	}
	if !IsNil(o.PeakDay) {
		toSerialize["peakDay"] = o.PeakDay
	}
	if !IsNil(o.TotalCreditsUsed) {
		toSerialize["totalCreditsUsed"] = o.TotalCreditsUsed
	}
	return toSerialize, nil
}

type NullableCumulativeCreditUsage struct {
	value *CumulativeCreditUsage
	isSet bool
}

func (v NullableCumulativeCreditUsage) Get() *CumulativeCreditUsage {
	return v.value
}

func (v *NullableCumulativeCreditUsage) Set(val *CumulativeCreditUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableCumulativeCreditUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableCumulativeCreditUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCumulativeCreditUsage(val *CumulativeCreditUsage) *NullableCumulativeCreditUsage {
	return &NullableCumulativeCreditUsage{value: val, isSet: true}
}

func (v NullableCumulativeCreditUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCumulativeCreditUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


