/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the ComponentDetailDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentDetailDocument{}

// ComponentDetailDocument struct for ComponentDetailDocument
type ComponentDetailDocument struct {
	Malware *bool `json:"malware,omitempty"`
}

// NewComponentDetailDocument instantiates a new ComponentDetailDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentDetailDocument() *ComponentDetailDocument {
	this := ComponentDetailDocument{}
	return &this
}

// NewComponentDetailDocumentWithDefaults instantiates a new ComponentDetailDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentDetailDocumentWithDefaults() *ComponentDetailDocument {
	this := ComponentDetailDocument{}
	return &this
}

// GetMalware returns the Malware field value if set, zero value otherwise.
func (o *ComponentDetailDocument) GetMalware() bool {
	if o == nil || IsNil(o.Malware) {
		var ret bool
		return ret
	}
	return *o.Malware
}

// GetMalwareOk returns a tuple with the Malware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDetailDocument) GetMalwareOk() (*bool, bool) {
	if o == nil || IsNil(o.Malware) {
		return nil, false
	}
	return o.Malware, true
}

// HasMalware returns a boolean if a field has been set.
func (o *ComponentDetailDocument) HasMalware() bool {
	if o != nil && !IsNil(o.Malware) {
		return true
	}

	return false
}

// SetMalware gets a reference to the given bool and assigns it to the Malware field.
func (o *ComponentDetailDocument) SetMalware(v bool) {
	o.Malware = &v
}

func (o ComponentDetailDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentDetailDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Malware) {
		toSerialize["malware"] = o.Malware
	}
	return toSerialize, nil
}

type NullableComponentDetailDocument struct {
	value *ComponentDetailDocument
	isSet bool
}

func (v NullableComponentDetailDocument) Get() *ComponentDetailDocument {
	return v.value
}

func (v *NullableComponentDetailDocument) Set(val *ComponentDetailDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentDetailDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentDetailDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentDetailDocument(val *ComponentDetailDocument) *NullableComponentDetailDocument {
	return &NullableComponentDetailDocument{value: val, isSet: true}
}

func (v NullableComponentDetailDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentDetailDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


