/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202601
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CreditBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditBalance{}

// CreditBalance struct for CreditBalance
type CreditBalance struct {
	CreditsRemaining *int32 `json:"creditsRemaining,omitempty"`
	CreditsUsed *int32 `json:"creditsUsed,omitempty"`
	PeriodEnd *string `json:"periodEnd,omitempty"`
	PeriodStart *string `json:"periodStart,omitempty"`
	PlanTier *string `json:"planTier,omitempty"`
	ResetDate *string `json:"resetDate,omitempty"`
	Status *string `json:"status,omitempty"`
	TotalCredits *int32 `json:"totalCredits,omitempty"`
	UsagePercentage *int32 `json:"usagePercentage,omitempty"`
}

// NewCreditBalance instantiates a new CreditBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditBalance() *CreditBalance {
	this := CreditBalance{}
	return &this
}

// NewCreditBalanceWithDefaults instantiates a new CreditBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditBalanceWithDefaults() *CreditBalance {
	this := CreditBalance{}
	return &this
}

// GetCreditsRemaining returns the CreditsRemaining field value if set, zero value otherwise.
func (o *CreditBalance) GetCreditsRemaining() int32 {
	if o == nil || IsNil(o.CreditsRemaining) {
		var ret int32
		return ret
	}
	return *o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsRemaining) {
		return nil, false
	}
	return o.CreditsRemaining, true
}

// HasCreditsRemaining returns a boolean if a field has been set.
func (o *CreditBalance) HasCreditsRemaining() bool {
	if o != nil && !IsNil(o.CreditsRemaining) {
		return true
	}

	return false
}

// SetCreditsRemaining gets a reference to the given int32 and assigns it to the CreditsRemaining field.
func (o *CreditBalance) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = &v
}

// GetCreditsUsed returns the CreditsUsed field value if set, zero value otherwise.
func (o *CreditBalance) GetCreditsUsed() int32 {
	if o == nil || IsNil(o.CreditsUsed) {
		var ret int32
		return ret
	}
	return *o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetCreditsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsUsed) {
		return nil, false
	}
	return o.CreditsUsed, true
}

// HasCreditsUsed returns a boolean if a field has been set.
func (o *CreditBalance) HasCreditsUsed() bool {
	if o != nil && !IsNil(o.CreditsUsed) {
		return true
	}

	return false
}

// SetCreditsUsed gets a reference to the given int32 and assigns it to the CreditsUsed field.
func (o *CreditBalance) SetCreditsUsed(v int32) {
	o.CreditsUsed = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *CreditBalance) GetPeriodEnd() string {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret string
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetPeriodEndOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *CreditBalance) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given string and assigns it to the PeriodEnd field.
func (o *CreditBalance) SetPeriodEnd(v string) {
	o.PeriodEnd = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *CreditBalance) GetPeriodStart() string {
	if o == nil || IsNil(o.PeriodStart) {
		var ret string
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetPeriodStartOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *CreditBalance) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given string and assigns it to the PeriodStart field.
func (o *CreditBalance) SetPeriodStart(v string) {
	o.PeriodStart = &v
}

// GetPlanTier returns the PlanTier field value if set, zero value otherwise.
func (o *CreditBalance) GetPlanTier() string {
	if o == nil || IsNil(o.PlanTier) {
		var ret string
		return ret
	}
	return *o.PlanTier
}

// GetPlanTierOk returns a tuple with the PlanTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetPlanTierOk() (*string, bool) {
	if o == nil || IsNil(o.PlanTier) {
		return nil, false
	}
	return o.PlanTier, true
}

// HasPlanTier returns a boolean if a field has been set.
func (o *CreditBalance) HasPlanTier() bool {
	if o != nil && !IsNil(o.PlanTier) {
		return true
	}

	return false
}

// SetPlanTier gets a reference to the given string and assigns it to the PlanTier field.
func (o *CreditBalance) SetPlanTier(v string) {
	o.PlanTier = &v
}

// GetResetDate returns the ResetDate field value if set, zero value otherwise.
func (o *CreditBalance) GetResetDate() string {
	if o == nil || IsNil(o.ResetDate) {
		var ret string
		return ret
	}
	return *o.ResetDate
}

// GetResetDateOk returns a tuple with the ResetDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetResetDateOk() (*string, bool) {
	if o == nil || IsNil(o.ResetDate) {
		return nil, false
	}
	return o.ResetDate, true
}

// HasResetDate returns a boolean if a field has been set.
func (o *CreditBalance) HasResetDate() bool {
	if o != nil && !IsNil(o.ResetDate) {
		return true
	}

	return false
}

// SetResetDate gets a reference to the given string and assigns it to the ResetDate field.
func (o *CreditBalance) SetResetDate(v string) {
	o.ResetDate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreditBalance) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreditBalance) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreditBalance) SetStatus(v string) {
	o.Status = &v
}

// GetTotalCredits returns the TotalCredits field value if set, zero value otherwise.
func (o *CreditBalance) GetTotalCredits() int32 {
	if o == nil || IsNil(o.TotalCredits) {
		var ret int32
		return ret
	}
	return *o.TotalCredits
}

// GetTotalCreditsOk returns a tuple with the TotalCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetTotalCreditsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCredits) {
		return nil, false
	}
	return o.TotalCredits, true
}

// HasTotalCredits returns a boolean if a field has been set.
func (o *CreditBalance) HasTotalCredits() bool {
	if o != nil && !IsNil(o.TotalCredits) {
		return true
	}

	return false
}

// SetTotalCredits gets a reference to the given int32 and assigns it to the TotalCredits field.
func (o *CreditBalance) SetTotalCredits(v int32) {
	o.TotalCredits = &v
}

// GetUsagePercentage returns the UsagePercentage field value if set, zero value otherwise.
func (o *CreditBalance) GetUsagePercentage() int32 {
	if o == nil || IsNil(o.UsagePercentage) {
		var ret int32
		return ret
	}
	return *o.UsagePercentage
}

// GetUsagePercentageOk returns a tuple with the UsagePercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditBalance) GetUsagePercentageOk() (*int32, bool) {
	if o == nil || IsNil(o.UsagePercentage) {
		return nil, false
	}
	return o.UsagePercentage, true
}

// HasUsagePercentage returns a boolean if a field has been set.
func (o *CreditBalance) HasUsagePercentage() bool {
	if o != nil && !IsNil(o.UsagePercentage) {
		return true
	}

	return false
}

// SetUsagePercentage gets a reference to the given int32 and assigns it to the UsagePercentage field.
func (o *CreditBalance) SetUsagePercentage(v int32) {
	o.UsagePercentage = &v
}

func (o CreditBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreditsRemaining) {
		toSerialize["creditsRemaining"] = o.CreditsRemaining
	}
	if !IsNil(o.CreditsUsed) {
		toSerialize["creditsUsed"] = o.CreditsUsed
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["periodEnd"] = o.PeriodEnd
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["periodStart"] = o.PeriodStart
	}
	if !IsNil(o.PlanTier) {
		toSerialize["planTier"] = o.PlanTier
	}
	if !IsNil(o.ResetDate) {
		toSerialize["resetDate"] = o.ResetDate
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TotalCredits) {
		toSerialize["totalCredits"] = o.TotalCredits
	}
	if !IsNil(o.UsagePercentage) {
		toSerialize["usagePercentage"] = o.UsagePercentage
	}
	return toSerialize, nil
}

type NullableCreditBalance struct {
	value *CreditBalance
	isSet bool
}

func (v NullableCreditBalance) Get() *CreditBalance {
	return v.value
}

func (v *NullableCreditBalance) Set(val *CreditBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditBalance(val *CreditBalance) *NullableCreditBalance {
	return &NullableCreditBalance{value: val, isSet: true}
}

func (v NullableCreditBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


