/*
Sonatype Guide API

REST API into [Sonatype Guide](https://guide.sonatype.com).

API version: 202607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeguide

import (
	"encoding/json"
)

// checks if the OrganizationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDTO{}

// OrganizationDTO struct for OrganizationDTO
type OrganizationDTO struct {
	Auth0OrgId *string `json:"auth0OrgId,omitempty"`
	IsBillingSubscriber *bool `json:"isBillingSubscriber,omitempty"`
	IsOwner *bool `json:"isOwner,omitempty"`
	Logo *string `json:"logo,omitempty"`
	Name *string `json:"name,omitempty"`
	People *int32 `json:"people,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewOrganizationDTO instantiates a new OrganizationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDTO() *OrganizationDTO {
	this := OrganizationDTO{}
	return &this
}

// NewOrganizationDTOWithDefaults instantiates a new OrganizationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDTOWithDefaults() *OrganizationDTO {
	this := OrganizationDTO{}
	return &this
}

// GetAuth0OrgId returns the Auth0OrgId field value if set, zero value otherwise.
func (o *OrganizationDTO) GetAuth0OrgId() string {
	if o == nil || IsNil(o.Auth0OrgId) {
		var ret string
		return ret
	}
	return *o.Auth0OrgId
}

// GetAuth0OrgIdOk returns a tuple with the Auth0OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetAuth0OrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.Auth0OrgId) {
		return nil, false
	}
	return o.Auth0OrgId, true
}

// HasAuth0OrgId returns a boolean if a field has been set.
func (o *OrganizationDTO) HasAuth0OrgId() bool {
	if o != nil && !IsNil(o.Auth0OrgId) {
		return true
	}

	return false
}

// SetAuth0OrgId gets a reference to the given string and assigns it to the Auth0OrgId field.
func (o *OrganizationDTO) SetAuth0OrgId(v string) {
	o.Auth0OrgId = &v
}

// GetIsBillingSubscriber returns the IsBillingSubscriber field value if set, zero value otherwise.
func (o *OrganizationDTO) GetIsBillingSubscriber() bool {
	if o == nil || IsNil(o.IsBillingSubscriber) {
		var ret bool
		return ret
	}
	return *o.IsBillingSubscriber
}

// GetIsBillingSubscriberOk returns a tuple with the IsBillingSubscriber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetIsBillingSubscriberOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBillingSubscriber) {
		return nil, false
	}
	return o.IsBillingSubscriber, true
}

// HasIsBillingSubscriber returns a boolean if a field has been set.
func (o *OrganizationDTO) HasIsBillingSubscriber() bool {
	if o != nil && !IsNil(o.IsBillingSubscriber) {
		return true
	}

	return false
}

// SetIsBillingSubscriber gets a reference to the given bool and assigns it to the IsBillingSubscriber field.
func (o *OrganizationDTO) SetIsBillingSubscriber(v bool) {
	o.IsBillingSubscriber = &v
}

// GetIsOwner returns the IsOwner field value if set, zero value otherwise.
func (o *OrganizationDTO) GetIsOwner() bool {
	if o == nil || IsNil(o.IsOwner) {
		var ret bool
		return ret
	}
	return *o.IsOwner
}

// GetIsOwnerOk returns a tuple with the IsOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetIsOwnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOwner) {
		return nil, false
	}
	return o.IsOwner, true
}

// HasIsOwner returns a boolean if a field has been set.
func (o *OrganizationDTO) HasIsOwner() bool {
	if o != nil && !IsNil(o.IsOwner) {
		return true
	}

	return false
}

// SetIsOwner gets a reference to the given bool and assigns it to the IsOwner field.
func (o *OrganizationDTO) SetIsOwner(v bool) {
	o.IsOwner = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *OrganizationDTO) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *OrganizationDTO) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *OrganizationDTO) SetLogo(v string) {
	o.Logo = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationDTO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationDTO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationDTO) SetName(v string) {
	o.Name = &v
}

// GetPeople returns the People field value if set, zero value otherwise.
func (o *OrganizationDTO) GetPeople() int32 {
	if o == nil || IsNil(o.People) {
		var ret int32
		return ret
	}
	return *o.People
}

// GetPeopleOk returns a tuple with the People field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetPeopleOk() (*int32, bool) {
	if o == nil || IsNil(o.People) {
		return nil, false
	}
	return o.People, true
}

// HasPeople returns a boolean if a field has been set.
func (o *OrganizationDTO) HasPeople() bool {
	if o != nil && !IsNil(o.People) {
		return true
	}

	return false
}

// SetPeople gets a reference to the given int32 and assigns it to the People field.
func (o *OrganizationDTO) SetPeople(v int32) {
	o.People = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *OrganizationDTO) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *OrganizationDTO) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *OrganizationDTO) SetSlug(v string) {
	o.Slug = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OrganizationDTO) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDTO) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OrganizationDTO) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OrganizationDTO) SetUrl(v string) {
	o.Url = &v
}

func (o OrganizationDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Auth0OrgId) {
		toSerialize["auth0OrgId"] = o.Auth0OrgId
	}
	if !IsNil(o.IsBillingSubscriber) {
		toSerialize["isBillingSubscriber"] = o.IsBillingSubscriber
	}
	if !IsNil(o.IsOwner) {
		toSerialize["isOwner"] = o.IsOwner
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.People) {
		toSerialize["people"] = o.People
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableOrganizationDTO struct {
	value *OrganizationDTO
	isSet bool
}

func (v NullableOrganizationDTO) Get() *OrganizationDTO {
	return v.value
}

func (v *NullableOrganizationDTO) Set(val *OrganizationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDTO(val *OrganizationDTO) *NullableOrganizationDTO {
	return &NullableOrganizationDTO{value: val, isSet: true}
}

func (v NullableOrganizationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


